### ISSUE TITLE
Manually Displaying Menu Under Mouse Pointer

### ISSUE THREAD

**Issue by SoftCircuits** [swisnl/jQuery-contextMenu#115]
I want to display the context menu when the user drops after a drag and drop operation.

```
function onDragStop(event, ui) {
    // Display drop menu
    $('#context-menu').contextMenu();
}
```

The code above displays the menu; however, it does not appear under the mouse as I'd like. Is there a way to have the menu appear at the current mouse coordinates?

**Comment by VhevhangVhakhikhang** [comment]
Where will I place the onDragStop function? How to make this working? I have an example ContextMenu Code.

    $.contextMenu({
        selector: 'input.form-submit',
        trigger: 'none',
        callback: function(key, options) {				         
        },
        items:{
            "sign": {name: "Sign...", icon: "edit"},
            "browse": {name: "Browse...", icon: "browse"},            
            "sep1": "---------",
            "clear": {name: "Clear", icon: "delete"}
       }
    });

     $('input.form-submit').contextMenu();

**Comment by bbrala** [comment]
You add the event to the element you enabled dragging on. Can't really say what that is without some code.
