### ISSUE TITLE
Submenu inherits class of parent menu item

### ISSUE THREAD

**Issue by Lajnold** [swisnl/jQuery-contextMenu#123]
When a menu item has a submenu, the `<ul>` for the submenu inherits the className property of the menu item.

For instance, in the example below, the submenu will have the `menu-item` class.

<pre>$.contextMenu({
    selector: '.context-menu-one',
    items: {
        "sub1": {
            name: "Item with submenu",
            className: 'menu-item',
            items: {
                "sub1": {
                    name: "Sub item 1",
                },
                "sub2": {
                    name: "Sub item 2",
                }
            }
        },
    }
});</pre>

It need not be a problem, as `menu-item` can be defined only for `<li>` elements, but I'm still thinking it may be a bug.

**Comment by bbrala** [comment]
Since the classes have been reworked, this is no longer relevant.
