### ISSUE TITLE
Enabling and disabling a context menu when the trigger is ‘hover’ does not seem to work

### ISSUE THREAD

**Issue by howardfoster** [swisnl/jQuery-contextMenu#125]
Disable a contextMenu trigger

disable contextMenu to be shown on specified trigger elements
$(".some-selector").contextMenu(false);

Enable a contextMenu trigger

enable contextMenu to be shown on specified trigger elements
$(".some-selector").contextMenu(true);

This works when trigger is 'right', but not when trigger is 'hover'.
-howard

**Comment by pi5** [comment]
Now sure why this issue was closed. As pointed out by @howardfoster disabling works, but re-enabling does not.

**Comment by bbrala** [comment]
I was doing quite the cleanup, guess this one slipped through. 

So basically, re-enabling the context menu after disabling is broken?

**Comment by pi5** [comment]
@bbrala Thats right. This happens only when the trigger is 'hover'.

**Comment by bbrala** [comment]
Cool thanks.

**Comment by bbrala** [comment]
Seems to be fixed in master, seems fine on https://swisnl.github.io/jQuery-contextMenu/demo/trigger-hover-autohide.html
