### ISSUE TITLE
incompatibility jquery-contextmenu <--> bootstrap.css

### ISSUE THREAD

**Issue by hartmut59** [swisnl/jQuery-contextMenu#126]
Bootstrap.css destro conextmenu 

without bootstrap.css
http://iarranger.ohost.de/contextMenu_ok.png

with bootstrap.cc
http://iarranger.ohost.de/contextMenu_bad.png

**Comment by bbrala** [comment]
Made changed to how icons work to help developers use different icons. Also, removed the .icon class in favor for a namespaced icon class.
