### ISSUE TITLE
jQuery Icon Support

### ISSUE THREAD

**Issue by patrickhousley** [swisnl/jQuery-contextMenu#129]
jQuery UI has a great selection of icons that could be used with the menu entries. However, your plugin does not support these icons out of the box. I have included the changes I make below in hopes of having this as the default icon support in this plugin.

line 1078 change if block to:
```javascript
// add icons
if (item.icon) {
     $('<span></span>', {
          'class' : 'ui-icon ui-icon-' + item.icon,
     }).prependTo($t);
}
```

**Comment by bbrala** [comment]
Fixed by craeting a callback option as icon value for an item. See #272
