### ISSUE TITLE
stale context menu on second registration for same selector

### ISSUE THREAD

**Issue by fabiankessler** [swisnl/jQuery-contextMenu#135]
doing $.contextMenu({}) with the same selector doesn't work as expected.
i did not debug it, but it seems that the script keeps the passed object from the first call.

my use case: i have a main div into which i create some divs and some of them get context menus attached, each gets its own. that works. then i use jquery's .empty() method, and start over. now my context menus that i re-create are wrong. same id's (selectors) but they should look different.

the solution i've found to work around this problem is:
        $.contextMenu('destroy', {
            selector: '#myId'
        });
before re-adding the new one.

i suggest to change this behavior, and overwrite the existing menu with the new one. 
if not, then i recommend documenting this.

btw it did not help to make my menu dynamic; returning with 'build' instead of 'items' directly. it took me a while to figure out and to find a workaround, so i really suggest a change or documentation.

**Comment by bbrala** [comment]
Cleanup, closing this issue.
