### ISSUE TITLE
sub menus not working with jquery 2.0

### ISSUE THREAD

**Issue by kipwilliams** [swisnl/jQuery-contextMenu#141]
Sub menus do not show when using jquery 2.0 because jquery animate adds overflow:hidden to menu item when animating and doesn't remove it.  This has been patched in 1.9 but not jquery 2.0 yet.  To fix this add to line 824 $(this).css("overflow", "visible"); // patch for bug in jquery animate.  Until 2.0 gets patched.

**Comment by bbrala** [comment]
Tested this, works as it should.
