### ISSUE TITLE
Context menus on an absolutely positioned scrolling div causes scrolling issue

### ISSUE THREAD

**Issue by Req** [swisnl/jQuery-contextMenu#143]
Issue is reproduced in IE 9 when the page contains a horizontal scrollbar, but not Chrome.

I have an position:absolute; set scrolling DIV that contains a list of elements with context menus. When I scroll down (screenshot 1) and open a context menu (screenshot 2) it works fine except that a vertical scrollbar appears. After that when I scroll up (screenshot 4) and open a context menu for the first item, the menu automatically scrolls down to the last element (screenshot 5), but opens a context menu for the first element (screenshot 6). The source for the test case I created can be found here: http://pastebin.com/NyZFZvTp

Here are screenshots of the steps taken in order:
![ctx1](https://f.cloud.github.com/assets/635732/541713/2711b34a-c214-11e2-900e-7b155bd88e4e.png)
![ctx2](https://f.cloud.github.com/assets/635732/541715/291186a2-c214-11e2-8db4-9e84bf2d68a5.png)
![ctx3](https://f.cloud.github.com/assets/635732/541716/2abf36de-c214-11e2-8f83-dcff995b9c73.png)
![ctx4](https://f.cloud.github.com/assets/635732/541718/2c6b669c-c214-11e2-9ac1-f8303f4cacf5.png)
![ctx5](https://f.cloud.github.com/assets/635732/541720/2dfc1c04-c214-11e2-8287-86f362f67dd9.png)
![ctx6](https://f.cloud.github.com/assets/635732/541722/2f798c60-c214-11e2-980d-0fd20316fe40.png)

The issue is for a single page app where that menu always has a lot of items in it, so this is a very common issue. The actual page is much more complicated and the menu is draggable in it, but I managed to track it down to the combination of position:absolute; and a scrollbar as seen in the test case. Help please!

**Comment by ishanishah06** [comment]
For resolving issue we can add jQuery scroll event
$("div").scroll(function(e)) {
          //Hide context menu code
});
so when user scroll then it hide context menu.

**Comment by bbrala** [comment]
Don't think i'll be handling this case in the plugin.
