### ISSUE TITLE
Support for dynamic items

### ISSUE THREAD

**Issue by endzeit** [swisnl/jQuery-contextMenu#15]
Hi,

This is a feature request rather than an issue ticket.
I would love to have the possibility to dynamically add items to a contextmenu at runtime.

The scenario: A contextmenu gets triggered and the menu items are created depending on info from the trigger element.
Like 'Add to' > [bunch of dynamic elements]

I tried to alter the `opt.commands` and `opt.items` objects in the show event of the contextmenu but with no effect.

One way to achieve this would be a `beforeRender` event where it's possible to replace the items created at registration with new ones.
Another way (seen at jjmenu plugin) is instead of a hardcoded item object literal one can use a function which provides context (of the trigger element) and returns a dynamically created item.

As a workaround (haven't tested this yet) it should be possible to register a click event with jQuery which then (functions as wrapper and) creates a  $.contextMenu with items in the context of the click event.
But this could get messy really quick with a lot of different trigger events.

I don't know if this functionality is within the designated scope of jQuery-contextMenu,
but it would greatly enhance the overall very good experience with this plugin. :)

Thanks.

**Comment by alexkrush** [comment]
Hi,
I'm trying to dynamically initialize menu from json data.

I've tried following html:
```javascript
<a id="17" class="Acceptance" href="..." onmouseup="setGlobalName(this)">02/26/2014</a>   
```
and following javascript:
```javascript
var globalName = "";
        function loadme() {
            return {
                "edit": { name: globalName },
            }
        };
        function setGlobalName(obj) {
            var id = obj.id;
            $.get(<url to json >, function (data) {
                var json = JSON.parse(data);
                globalName = json["<SomeField>"];
            });
        };
        $(function () {
            $.contextMenu({
                selector: '.Acceptance',
                build: function ($trigger, e) {                  
                    return {                    
                        items: loadme()
                    };
                }
            });
        });
```
I'm getting on first click empty menu:
![image](https://cloud.githubusercontent.com/assets/6331365/6805621/3d024984-d244-11e4-8333-f6d53f7dea6a.png)

 and only on the second click the right one:
![image](https://cloud.githubusercontent.com/assets/6331365/6805843/80d67940-d245-11e4-9247-4ef8315ed387.png)

Could you advice me please why I'm getting this effect and how to correct it?
Thanks a lot in advance,
Alexander

**Comment by ajtis** [comment]
My solution for generation of context menu for each row getting option from other drop down menu (clone options)

`$(function(){
    $.contextMenu({
        selector: '.fileManagerTable tbody tr',
        build: function($trigger, e) {
            var setup= {
                callback: function(key, options) {
                    var m = "clicked: " + key;
                    window.console && console.log(m) || alert(m);
                },
                items:{}
            };
            console.log($trigger);

            $('.row-group-actions li',$trigger).each(function () {
                var item=$(this);
                var actionText=item.text();
                if(item.data('icon')){
                    setup.items[actionText]={name: actionText,icon:item.data('icon')};
                }
                else{
                    setup.items[actionText]={name: actionText};
                }

            });

            return setup;
        }
    });
});`
