### ISSUE TITLE
Uncaught TypeError - 'contextMenu'

### ISSUE THREAD

**Issue by onlyDLucky** [swisnl/jQuery-contextMenu#165]
Hi all!

We created a button to display the context menu so that the context menu is supposed to be displayed when we clicked on that button.

We used the correct javascript or css references, such as "jquery-1.7.min.js", "jquery.contextMenu.js", and "jquery.contextMenu.css". And the we used to create the context menu as shown below:

//some previous codes here...
//...
$.contextMenu({
                    selector: "#" + obj.id.toString(),
                    trigger: 'left',
                    callback: function (key, options) {
		//some codes here
                    },
                    items: menuItems
                });                
}

The issue is that the context menu was not displayed when we clicked on the button. We used the GoogleChrome (version 29.0.1547.62 m) and in the chrome's console we noticed that we get the following error:

Uncaught TypeError: Object function (a,b){return new e.fn.init(a,b,h)} has no method 'contextMenu'.

We have tried to solve this issue but we cannot find any solution. Would you please help us to solve this issue? Any solution is really appreciated.

Thank you.

**Comment by bbrala** [comment]
Hehe, wrong plugin mate. This is jquery-contextMenu not the same as you have in your scripttag.
