### ISSUE TITLE
Radio button name "undefined" on 

### ISSUE THREAD

**Issue by dbuerer** [swisnl/jQuery-contextMenu#175]
I'm using the getInputValues function in the hide event to get the values of all input elements, in my case radio elements and text elements, in the menu as such
<CODE>
values=$.contextMenu.getInputValues(opt);
</CODE>

When i look at the object values, the text elements have names, the radio button has a name of undefined

the menu is created as a submenu using the following definition:

<CODE>
menuItems['reqType']={name:'Type',items:{ 
		'reqType0':{name:'Text',label:'reqType',type:'radio',value:0,selected:false},
		'reqType1':{name:'Revision History',label:'reqType',type:'radio',value:1,selected:false},
		'reqType2':{name:'Document',label:'reqType',type:'radio',value:2,selected:false},
		'reqType3':{name:'Part Numbers',label:'reqType',type:'radio',value:3,selected:false},
		'test1':{name:'mon ami some data if you please',type:'text'}
	   }			
	};
</CODE>

**Comment by bbrala** [comment]
Radio is the group for the radio button.
