### ISSUE TITLE
Context-menu resizes when (re)opening it. 

### ISSUE THREAD

**Issue by RubenBosch** [swisnl/jQuery-contextMenu#183]
Within my firefox 'Inspector', I noticed the [ul class=' context-menu-root'] receives an width-property on opening the context-menu for the first time. 
After closing the object and re-opening it, the width-property changes (in my implementation, it shrinks, on your implementation (for example: http://medialize.github.io/jQuery-contextMenu/demo.html), it grows one pixel, each time you close and re-open the contextmenu.

**Comment by bbrala** [comment]
Had this been fixed? Think it has been with a recent change.
