### ISSUE TITLE
Chrome/IE bugs when re-opening context menu on a different element

### ISSUE THREAD

**Issue by mikzat** [swisnl/jQuery-contextMenu#186]
I am using RaphaelJS to draw some stuff on a canvas, then assigning right-click menus to different elements via selectors:
selector: '#' + name + ' svg circle'
selector: '#' + name + ' svg image'
selector: '#' + name + ' svg path'

Chrome (Version 32.0.1700.72 m): 
Opening context menu on the same element works fine, then trying to open it on another element causes a "crash", menu disappears but the invisible overlay remains on the screen preventing further interaction with anything until the whole page is refreshed:
http://screencast.com/t/uqMsJxb5FjDC

IE10:
When opening context menu on an element, then trying to open context menu on another element, the right-click target remains whatever the first element that was right-clicked instead of the new one:
http://screencast.com/t/BgMGO54MXxq

Both issues seem to be related to the target of the right-click when the "context-menu-layer" is on the screen.

Commenting out lines 362-406 in the "setTimeout" block of "layerClick" fixes both issues. What is the intended purpose of this code and what unintended side effects can I expect from deleting these lines?

**Comment by bbrala** [comment]
CLosing for now, reopen if you still have this. The fiddle has way to low jquery and such to check
