### ISSUE TITLE
Menu width increasing while toggling disabled command

### ISSUE THREAD

**Issue by vrpruthvi** [swisnl/jQuery-contextMenu#197]
ContextMenu width is increasing when the toggle option is clicked.
Source:http://medialize.github.io/jQuery-contextMenu/demo/disabled-changing.html
Try clicking on the toggle option again and again to see increase in menu width.

**Comment by toothbrush7777777** [comment]
Yes, I also noticed this.
Is there any way of fixing this?

**Comment by Dgc2002** [comment]
I was able to fix this here: https://github.com/medialize/jQuery-contextMenu/pull/262

**Comment by bbrala** [comment]
Fixed, thanks for pointing in the right direction dgc2002
