### ISSUE TITLE
Opening a second menu: root.$layer is undefined

### ISSUE THREAD

**Issue by Pancakeo** [swisnl/jQuery-contextMenu#212]
This is a duplicate of https://github.com/medialize/jQuery-contextMenu/issues/105 , which should be re-opened.

Happy to provide detailed repro steps, if needed.

Will also try to fix, as I'm fairly certain the maintainer is dead :)

**Comment by Zh3d** [comment]
Hi, I have the same issue...

Did you have fixed this issues ?

I'm trying also to fix it :-(

**Comment by bbrala** [comment]
Zh3d, can you give the steps to reproduce the error?

**Comment by andreasrosdal** [comment]
Hi!  I also get the same problem with https://play.freeciv.org which uses this contextMenu.
The error reported by the browser is this:  "Cannot read property 'hide' of undefined"

This is the source code line in question:  
https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L443

<img width="523" alt="contextmenu-bug" src="https://cloud.githubusercontent.com/assets/210993/11451389/1fc273e0-95c5-11e5-8a77-e5a04d311fc0.png">

**Comment by bbrala** [comment]
Kind of hard for me to debug without steps to reproduce. I kind of need a context or steps to reproduce.

**Comment by andreasrosdal** [comment]
I've created a pull-request to fix this. I'm not able to reproduce the problem myself, but after running with this fix in production on https://play.freeciv.org for some hours the problem has not occurred again.

**Comment by bbrala** [comment]
i don't really like to merge a fix for something there is not a real defined problem for. But i'll merge this since it cant really break anything and you haven't been the first to notice.
