### ISSUE TITLE
Hiding menu manually causes error

### ISSUE THREAD

**Issue by christophlutz** [swisnl/jQuery-contextMenu#230]
I am using the context menu as a plugin for the jquery fancytree. I need to hide the menu manually on certain actions that open modal windows. When I do this like so $(".fancytree-title").contextMenu("hide"); the menu hides but when the modal window closes, the menu code still wants to trigger the close action on line 740:

root.$menu.trigger('contextmenu:hide');

I get the error  'Unable to get property trigger of undefined or null reference' - obviously because I have closed the menu manually already. How can I prevent the triggering on the callback?

**Comment by bbrala** [comment]
This is weird, since the trigger is triggered on itemClick. Could you maybe create a testcase on http://jsfiddle.net/?

**Comment by christophlutz** [comment]
thanks for responding to this. Hmm, I have parked this, not sure if it's still an issue, but if it is I will respond, thank you.

**Comment by bbrala** [comment]
Ok, ket us know. Ill close the issue for now.
