### ISSUE TITLE
Multiple context menus on a page doesn't work

### ISSUE THREAD

**Issue by tactics2** [swisnl/jQuery-contextMenu#232]
Trying to put several different context menus on a single page. When I use this:

$(function(){
    $('#primary-nav').contextMenu({
        selector: 'a', 
        items: {
           "new": {name: "Open in new tab"}
        }
    });
});

$(function(){
    $('.entity-list').contextMenu({
        selector: 'td', 
        items: {
           "new": {name: "Open a new tab"},
		    "edit": {name: "Edit"},
			 "delete": {name: "Delete"}
        }
    });
});

I get context menus on every link on my page, not just the ones inside of #primary-nav

**Comment by bbrala** [comment]
@tactics2 have you tried this solution?
