### ISSUE TITLE
item's callback case something uncorrect

### ISSUE THREAD

**Issue by ahalf-xq** [swisnl/jQuery-contextMenu#237]
**I get the demo and run it, then something uncorrect happened:when the right-click mouseup, there is a chance that the menu will disapper(by click the item close to clickPoint).why?**

    $.contextMenu({
        selector: '#demotest', 
        callback: function(key, options) {
            var m = "clicked: " + key;
            // window.console && console.log(m) || alert(m); 
            console.log(m)
        },
        items: {
            "edit": {name: "Edit"},
            "cut": {name: "Cut"},
            "copy": {name: "Copy"},
            "paste": {name: "Paste"},
            "delete": {name: "Delete"}
        }
    });
(when I right-click to apply the contextMenu,the context show and disapper right now,and generate a console "clicked:delete"..)

**Comment by bbrala** [comment]
Cant reproduce this issue. Is this still relevant?
