### ISSUE TITLE
jQuery second contextMenu don't show properly

### ISSUE THREAD

**Issue by germanmartin** [swisnl/jQuery-contextMenu#238]
I have a big div (the blue one) with a ContextMenu and inside another div (green one) with another contextmenu. Both contextmenu shows with right click.

If I make a right clic in the blue div the ContextMenu shows fine. But when I clic in the green div still appears the old contextmenu. If I refresh the page and just clic in the green div, it shows the correct contextMenu.

I made this example http://jsfiddle.net/german_martin/oprkvys1/ of my problem.

    
<div class="CuadroFondo">
    <div class="SingleItem">ITEM 1</div> 
    <div class="SingleItem">ITEM 2</div> 
    <div class="SingleItem">ITEM 3</div> 
    </div>
    

    
$(document).ready(function () {

    $.contextMenu({
        selector: '.CuadroFondo',
        callback: function (key, options) {

            if (key == "expand") {
                alert("expand");
            }

            if (key == "creargrupo") {
                alert("creargrupo");
            }

            if (key == "seguridadgrupo") {
                alert("jejeje")
            }

        },
        items: {
            "expand": { name: "Irak", icon: "add-expand" },
            "sep1": "--MAIN MENU--",
            "creargrupo": { name: "Afganistan", icon: "crearnuevo" },

        }
    });

    $.contextMenu({
        selector: '.SingleItem',
        callback: function (key, options) {

            if (key == "expand") {
                alert("expand");
            }

            if (key == "creargrupo") {
                alert("creargrupo");
            }

            if (key == "seguridadgrupo") {
                alert("jejeje")
            }

        },
        items: {
            "expand": { name: "Miami", icon: "add-expand" },
            "sep1": "--SUBMENU--",
            "seguridadgrupo": { name: "Florida", icon: "seguridad" }

        }
    });

})

**Comment by germanmartin** [comment]
Can anyone help me with this issue?

**Comment by azza0091** [comment]
same problem for me... could anyone solve this please? is really annoying...

**Comment by bbrala** [comment]
Hmm pretty interesting, it seems it is broken only until you click to close the menu and open it again.

http://jsfiddle.net/oprkvys1/2/

**Comment by germanmartin** [comment]
Hi! With your example ( http://jsfiddle.net/oprkvys1/2/ ) I have the same problem. 

=(

**Comment by bbrala** [comment]
Yeah was just checking if I could reproduce the problem. :)

**Comment by germanmartin** [comment]
Great, thanks for your check!

**Comment by bbrala** [comment]
I thin k this had been fixed, i cannot reproduce anymore in: http://jsfiddle.net/oprkvys1/3/

**Comment by germanmartin** [comment]
This is not fixed. 
Try it: http://jsfiddle.net/oprkvys1/3/

1. Make right clic in the green square and you will get "Miami Florida"
2. Make right clic outside (in blue background) and you will get "Irak Afganistan"
3. Then right make clic in the green square again and you will NOT get "Miami Florida", you will get "Irak Afganistan"

**Comment by germanmartin** [comment]
Thank you!! It works using reposition:false,
