### ISSUE TITLE
variablize the items parameter

### ISSUE THREAD

**Issue by schmidtl4** [swisnl/jQuery-contextMenu#242]
In my application, an administrator can add/delete tables in a database.
When the user loads the app, an ajax call is made to populate the table list to ensure that all recent table changes are reflected in the UI. The user can then switch from one table to another,

How do I use the table list retrieved from the db (obviously formatted to a string needed by contextMenu's items: ) in a contextMenu?  This (i.e. hardcoded) works fine:
                       $.contextMenu({
				selector: '.select_list', 
				trigger: 'hover',
				callback: function(key, options) {
					change_list(key);  // a function to get data from db and redisplay page
				},
				items: {
					"all": {name: "All"},
					"TableA": {name: "TABLEA"},
					"TableB": {name: "TABLEB"},
					"TableC": {name: "TABLEC"}
				}
			});

I'd like to assign the whole items: string (form { to }) to a variable and use that instead.  Is that possible?

When I try it (checking carefully to ensure the string is identical to the above), I get a jQuery error: 
    TypeError: invalid 'in' operand a

**Comment by cibernox** [comment]
Also something I want. The solution for me could be allow items to be a function (apart form an array like now)

That would allow the user to fully customize the menu in any way they want, by example change the text of an items from "Copy" to "Copy 8 items" depending of some external selection.

**Comment by amenadiel** [comment]
| When I try it (checking carefully to ensure the string is identical to the above), I get a jQuery error: 

items isn't supposed to be a string. It's an object. You can try declaring it beforehand:

```js
var menuitems={
            edit: {name: "Edit", icon: "edit"},
            cut: {name: "Cut", icon: "cut"},
            copy: {name: "Copy", icon: "copy"},
            paste: {name: "Paste", icon: "paste"},
            delete: {name: "Delete", icon: "delete"},
            sep1: "---------",
            quit: {name: "Quit", icon: "quit"}
        };

    $.contextMenu({
        selector: '.context-menu-one', 
	callback: function(key, options) {
	    var m = "clicked: " + key;
	    window.console && console.log(m) || alert(m); 
	 },
	items: menuitems
    });
```

If you retrieve the menuitems variable with an Ajax call, and the backend sends a properly formatted json, you can have jQuery parse it so you don't have to, and instantiate the contextMenu using that object as `items`

```js
$.ajax({
    url:'/backend/tables.php',
    type:'GET',
   dataType:'json'
}).done(function(jsonResponse) {

    $.contextMenu({
        selector: '.context-menu-one', 
	callback: function(key, options) {
	    var m = "clicked: " + key;
	    window.console && console.log(m) || alert(m); 
	 },
	items: jsonResponse
    });

});
```

don't try to manually mimic or parse json. It won't work and it's meant to be machine readable.

**Comment by bbrala** [comment]
This seems answered, thank you @amenadiel. :)
