### ISSUE TITLE
Use Font Awesome Icon in Menu

### ISSUE THREAD

**Issue by rjha999** [swisnl/jQuery-contextMenu#249]
How can I use font awesome Icon in this Jquery context Menu? Please help me for this.

**Comment by AndreaCatania** [comment]
I've made 2 simple changes that allow to use FontAwesome, if will be accepted you can use it easly.

**Comment by genachka** [comment]
+1

**Comment by bbrala** [comment]
Should be able to do this with the callback option :)

**Comment by genachka** [comment]
Seems a bit inefficient to do that via callback. Having a class(es) name
option on icon that would work as an override of default class(es) during
configuration would think to be better and easier for use.

**Comment by bbrala** [comment]
Yeah it is slightly more inefficient, but not by much if you just return a icon string. By changing the way it works when you just add a string we would break old code everywhere. I rather not break backwards compatibility. The callback also serves some other purposes like making the icon dependant on the state of something else.

I'm not ready to break backwards compatibility on this. I would consider this only when there might be a redo of the way the css is structured, but i don't feel confortable doing that yet.
