### ISSUE TITLE
Reverting value of a select

### ISSUE THREAD

**Issue by wkorfhage** [swisnl/jQuery-contextMenu#254]
I have a menu that has a select, and a clickable "revert" item to revert the select to some previous value, and I am having trouble getting it to work properly. The select in the context menu determines something that shows on the web page and which is also stored in a separate data structure. Upon showing the context menu, the selected item is set from that stored value with setInputValues.When the context menu hides, I get the current value of the select with getInputValues and store that away. That part works fine, but the "revert" item on the context menu is supposed to reset that separately stored state to a default value, and that isn't happening because of a sequence of events with shows, clicks and hides.

Just to be clear, suppose the select has values A, B and C, and A is the default value. If I right-click on the page and pick C, that gets stored, and will show as the selected item next time I bring up the context menu again. If I right-click on the page and click on revert, then next time I show the context menu, A should be selected, not C. My problem is that the actions taken by clicking "revert" are undone by my hide handler.

The crux of the problem is that getInputValues directly reads the current, immediate state of the select element in the context menu, but there doesn't seem to be a way to set the current of the select. When I click revert, all the stored state is set correctly, and I even try a call to setInputValues, but after that the hide handler gets invoked, and it ignores the stored state, reads the select which shows the old non-reverted value, and overwrites the stored state with that value. To go back to the example, when I click revert, the stored state is set to A, but when the context menu hides, it finds C still showing on the select and overwrites my reverted state with that value. In the end, the revert doesn't work.

I can solve this by storing state someplace to indicate that a revert is in progress, and act accordingly in the hide handler, but I was wondering if there was a more elegant method of forcing the select value to change when I click revert, so the hide handler can take that value. It would have the advantage of immediately reflecting the reversion in the context menu, rather than only showing it next time I bring up the menu.

**Comment by bbrala** [comment]
If you use the [callback](http://swisnl.github.io/jQuery-contextMenu/docs/items.html#callback) to define the reset, you could use the second argument of the callback, these are the runtime options and contain the real inputs (see [runtime options](http://swisnl.github.io/jQuery-contextMenu/docs/runtime-options.html) and the [inputs property](http://swisnl.github.io/jQuery-contextMenu/docs/runtime-options.html#inputs).

Think you should be able to do this with those properties?
