### ISSUE TITLE
On demand menu not working on iOS

### ISSUE THREAD

**Issue by vAlmaraz** [swisnl/jQuery-contextMenu#260]
I am developing a website with this library and I have to build context menu on demand with left trigger.
Some customers complaint about it doesn't work on iOS.
I checked demo website, it doesn't work:
http://medialize.github.io/jQuery-contextMenu/demo/dynamic-create.html
Also I have done a simple modification of demo code to trigger from left click and it doesn't work.

I have seen this bug:
https://github.com/medialize/jQuery-contextMenu/issues/83
Could it be related to the same issue, and maybe it has not been fixed in on demand feature?

Thank you

**Comment by vAlmaraz** [comment]
I have solved it adding:
$('.context-menu').on('click', function() {});
on line 1327, after $document.on({});

In my case, all context menu triggers have "context-menu" class.

**Comment by bbrala** [comment]
Yeah, its the issue that iOS needs an onclick handler.

onclick="void('iOS needs this');" 

You can see that on the left click demo.

**Comment by vAlmaraz** [comment]
Hi @sanjaykumar2338 

I am sorry but it seems the library has changed a bit since I made the change. And I am not working on the project any more.

I think I added it when initializing listeners. Maybe looking at the latest version when I posted the message you can find the line I talked about.

PD: I have edited my message to clarify the changes I made.

**Comment by bbrala** [comment]
@vAlmaraz could you open a new issue for this so i can track it there?

**Comment by sanjaykumar2338** [comment]
@bbrala 
I have create a new issue https://github.com/swisnl/jQuery-contextMenu/issues/628
