### ISSUE TITLE
Sub-Menu not closed when close and re-open the context menu.

### ISSUE THREAD

**Issue by mukeshmishra996** [swisnl/jQuery-contextMenu#273]
open the context menu then open the sub-menu without closing of sub-menu click on out side of context menu. again open the context menu. still sub menu is in open state.

**Comment by bbrala** [comment]
Did you add the line:

onclick="void('iOS needs this');" on the contextmenu element?

**Comment by bbrala** [comment]
Check out the documentation for: http://swisnl.github.io/jQuery-contextMenu/docs.html#reposition

Tha option controls if the contextmenu will be rebuilt or just repositioned.
