### ISSUE TITLE
Having problem with propagation to parent div's.

### ISSUE THREAD

**Issue by tlemmons** [swisnl/jQuery-contextMenu#281]
I am using a right click trigger and the parent actions are activating which moves the div.  Make the context menu out of place.  Is there a way to stop event propagation to parent handlers?

**Comment by bbrala** [comment]
Hmm, could you post a jsfiddle maybe to demonstrate?

**Comment by bbrala** [comment]
Closing this for now. If you have any updates, just reopen it.
