### ISSUE TITLE
Preventing the menu to show

### ISSUE THREAD

**Issue by tatsujin1** [swisnl/jQuery-contextMenu#282]
I'm using a callback to generate the menu items at run time, and in some cases (I'm building menus for table cells) there just isn't any relevant menu to show.
What I'm doing now is return `null` from the callback. It essentially works, but contextMenu complains in the console with the errors:
```
No items specified to show in contextMenu
Uncaught Error: No Items specified
```
So it feels a bit dirty. :)

Is there a (better) way, or is this lacking?

**Comment by bbrala** [comment]
Hmm, i think you need to return false in the build function to make it stop i think.

http://swisnl.github.io/jQuery-contextMenu/docs.html#options-build

"the build callback may return a boolean false to signal contextMenu to not display a context menu"

**Comment by tatsujin1** [comment]
Ah!  I missed that completely... Indeed it works, thanks! :)
