### ISSUE TITLE
Check and flesh out documentation

### ISSUE THREAD

**Issue by bbrala** [swisnl/jQuery-contextMenu#285]
The documentation is quite lacking in some parts as mentioned by @richpri in #284. Lets use this issue as a home for optimizing the documentation.

**Comment by richpri** [comment]
OK - I just spent 2 hours searching through the code in the
file source/jquery.contextMenu.js in the master branch in
hopes of finding a starting point for documenting the "opt"
object. It was what I suggested should be done in #284.

Nowhere in the code could I find a statement that defined
or initialized "opt". It and its elements are used a lot 
but it is never by itself on the left of an assignment
statement. Am I missing something? Colour me confused. 
Rich

**Comment by bbrala** [comment]
I'm sorry to hear that. The opt you get when you are inside the callbacks is pretty much a reference to the  contextmenu instance with things as a reference, like the menu elements and the items with the dom elements.

If you look at line 323 you see the following code.

     op.show.call($this, e.data, e.pageX, e.pageY);

I've quickly looked through the differen op.???.call statements, and it does seem the object that is passen isn't always the same, that might need some experimenting on the different callbacks to see if the data you get is somewhat consistent because it seems the build gives you a different set of data. 

My first guess is though that the current documentation does inform about the most important references to objects you might need but it is a bit too hard to read. 

I'm not sure yet how i would start the process of better documenting this. I need to think a little more about that.

**Comment by bbrala** [comment]
Updated at least the structure and some wording on the documentation. Also the layout might make it more readable. I will merge this soon and update the github.io page after that.

See PR #286

**Comment by bbrala** [comment]
As mentioned in #306, opt.$node it not sorrect. It should be opt.$selected possibly.

**Comment by bbrala** [comment]
And confirmed in #306

**Comment by bbrala** [comment]
Closing this one for now.
