### ISSUE TITLE
How manually show contextmenu and automatically show a specific submenu item open?

### ISSUE THREAD

**Issue by genachka** [swisnl/jQuery-contextMenu#292]
I've seen that $({selector}).contextMenu() will manually show a contextmenu, but I'd like to also automatically expand a specific submenu's item?

**Comment by bbrala** [comment]
There are commands like nextcommand which help you move the cursor. http://swisnl.github.io/jQuery-contextMenu/docs/events.html#nextcommand 

You might be able to do it with triggering a mouseover on the item, which you could select by using the className. You can define the classname in the item definiton http://swisnl.github.io/jQuery-contextMenu/docs/items.html#classname.

Hope that helps.

**Comment by genachka** [comment]
On a closed menu, I want to open it, and move to the 3rd item to force that item's submenu to expand. Can you show an example how to trigger the nextcommand event on such a case?

**Comment by bbrala** [comment]
Try the following javascript on the demo page.

```javascript
$('.context-menu-one').contextmenu();
$('.context-menu-one').data('contextMenu').$menu.trigger('nextcommand').trigger('nextcommand').trigger('nextcommand');
```

Hope that helps.
