### ISSUE TITLE
Demo is broken (Custom command)

### ISSUE THREAD

**Issue by ITgeek123** [swisnl/jQuery-contextMenu#294]
Hi,

Nothing urgent but just to notify on this demo is  broken.

http://swisnl.github.io/jQuery-contextMenu/demo/custom-command.html

Thanks.

P.S. I like this plugin very much. 
Thanks for maintaining it.=)

**Comment by bbrala** [comment]
Thanks for the compliment :+1: 

What is broken? It seems the click doesn't show the specific label that is clicked, is that what you mean?

**Comment by bbrala** [comment]
Closing this for now. If you have any updates, just reopen it.

**Comment by Ivanca** [comment]
@bbrala Yes that's what he meant, any idea how to make it work? I need to something just like it.

**Comment by Ivanca** [comment]
@bbrala Better, but the code still doesn't work, it should print `console.log('Clicked on ' + $(this).text());` but it never does (default behavior instead)
