### ISSUE TITLE
Event handler keyup fails when selected element is null

### ISSUE THREAD

**Issue by Chris7** [swisnl/jQuery-contextMenu#295]
In line 613 of jquery.contextMenu.js, 

```
if (typeof opt.$selected !== 'undefined') {
   opt.$selected.trigger(e);
}
```

If opt.$selected is null, this will fail and stop propagation. It should compare against null as well.

**Comment by bbrala** [comment]
Thank you for reporting. I will look at it as soon as possible.

**Comment by bbrala** [comment]
Hmm, yeah, null is an object not undefined.

**Comment by Chris7** [comment]
Thanks for fixing this!

**Comment by bbrala** [comment]
No problem :)
