### ISSUE TITLE
opt.$node is not populated on callbacks

### ISSUE THREAD

**Issue by Erika31** [swisnl/jQuery-contextMenu#306]
When click on a menu item, the callback function receives "opt" variable as second argument, which does not contain any "$node" property, as documented...

**Comment by bbrala** [comment]
Hmm, that is weird. I've investigated this and it seems the correct variable to get the selected list item is opt.$selected, which is different from what the documentation says, the opt.$node property is only populated when submenus are opened.

Would using $selected fix your problem? And ill make a task to update the documentation at #285

**Comment by Erika31** [comment]
The problem is that opt.$selected is NULL in my case...
And none of the opt properties can result in determining clicked node...
Very frustrating, as it should be the base in callback context !!!

**Comment by bbrala** [comment]
That is kinda weird. Could you supply me with a code sample?

**Comment by Erika31** [comment]
Here it is : http://jsfiddle.net/ErikaDH/ow8ye706/

**Comment by bbrala** [comment]
Thanks for the fiddle, ill have a look soon. The pull request #309 might actually be related to this.

**Comment by bbrala** [comment]
Ok, i checked it out, and you really shoudl use $selected. I need to change the documentation to make sure it is documented that way. 

The $node parameter is used to position submenu's and such, so is almost never populated. The $selected is tho.

See: http://jsfiddle.net/nLe5k2dp/

**Comment by Erika31** [comment]
Ok. Thanks.

Let's go for opt.$selected ;-)

**Comment by bbrala** [comment]
No problem, glad i could be of help :)
