### ISSUE TITLE
icon function parameters are wrong 2.0

### ISSUE THREAD

**Issue by RareDevil** [swisnl/jQuery-contextMenu#309]
I have tried to use a function as a icon like the example in docs (http://swisnl.github.io/jQuery-contextMenu/docs/items.html#icon) but that dont work as intended. $itemElement is a string. 
What i can see the problem is that "item._icon = item.icon.call(this, $t, key, item);" dont work as intended, there is only send $t, key, item to the function.
I have made a jsfiddle that shows the problem http://jsfiddle.net/RareDevil/hjs25p6q/

I'm still looking at this problem to see if i can find a solution for this problem and fix it.

EDIT: I have looked more into this problem and of what i can see then the problems is around line 1282 "item._icon = item.icon.call(this, $trigger, key, item);" something here dont add up for me here nor on line 1193 "item._icon = item.icon.call(this, $t, key, item);". 
Of what i can understand then this is how the function should look:
function ($trigger, itemKey, item) {
  // do stuff here...
  // this referrer to the "this" in the .call(). 
}
but if the functions is made like that then it will fail if its called from line 1193 "item._icon = item.icon.call(this, $t, key, item);" since its not the same data that is used as on line 1282 "item._icon = item.icon.call(this, $trigger, key, item);".

**Comment by bbrala** [comment]
Thanks for taking the time to make a pullrequest. Ill have a look later this week. I'll check the old doumentation to see if it has been an error in converting the documentation or it really is a bug. I think this is the same is issue #306

**Comment by RareDevil** [comment]
It looks like it. I do not know if there was thought about how the .call() function works. It seems to me that where the problem is. .call() is made so that the first argument that set will be used to set this in the function its used on and the arguments after is going to be the arguments in the function.

**Comment by bbrala** [comment]
Thanks again for helping out here. Merged the icon fix.
