### ISSUE TITLE
more functions to control the menu

### ISSUE THREAD

**Issue by RareDevil** [swisnl/jQuery-contextMenu#311]
Is there any plans on adding functions to fx add or remove items in the menu ?
I would like to be able to do the following:
Add / remove item
Disable / Enable item
Show / Hide item
Change item

I have done most of this right now in a jQuery widget, but i dont like that i have to recreate the menu everytime one of the functions are used.

**Comment by RareDevil** [comment]
I have been looking at doing this but i can see that i need to understand more about what happens in the code so it may take some time before i have a pull request with features i would like. 
@bbrala Is there any plans on making those functions from your end?

**Comment by bbrala** [comment]
I've been thinking about this, what are you trying to do? I kinda feel the recreation of the menu is not really a problem. You do have acces to some of the elements when  you add a custom callback to the menu, so you should be able to at least manually access the elements. 

The code to show/hide an menu item based on some external call without rebuilding the menu i think would be quite hard to do in its current structure.  I'd advise stick to rebuilding :)

So just to be clear, i have no plans to implement such functions. Just use the build callback.

**Comment by RareDevil** [comment]
I have been looking more at the documentation and found that Disable / Enable / Show / Hide item are not really needed anymore since you are now able to use a function on each item to control that.
But what i really want is a function like this:
$('#ContextmenuSelector').contextmenu("addItem", {copy: {
            name: "Copy",
            callback: function(key, opt){
                alert("Clicked on " + key);
            }
        }}); 
But i cant find a good way to do this so i have decided to stick with the rebuilding of the menu.

**Comment by swatiwak** [comment]
How to disable any particular item?

Any help will be appreciated.

**Comment by RareDevil** [comment]
@swatiwak if you look at the documentation then you can find all the information that you need. 
If you look here https://swisnl.github.io/jQuery-contextMenu/docs/items.html#disabled you can read about how to disable an item.

But this is an old and closed issue as it was not possible to do what I wanted.
