### ISSUE TITLE
add the radio button,  the callback seems not to be fired.

### ISSUE THREAD

**Issue by anna647** [swisnl/jQuery-contextMenu#322]
hello! if i add a radio button,it seems that after i click the radio, the callback seems not to be fired.  I write just like as follows:

$.contextMenu({
	selector: '.context-menu-one',
	callback: function() {
		alert("ttt");
	},
	items: {
				nowvalue: { 
                                     name: "radio1",
                                     type:'radio', 
                                     radio: 'color', 
                                     value:1, 
                                     className:'color-radio' },
				}
			});

Or if I want fire the event I should use it like this?

$('body .color-radio input').on('click',function(){
    alert("ttt");
})

**Comment by RareDevil** [comment]
Here is a fiddle that shows how to handle radios in the contextmenu.
http://jsfiddle.net/RareDevil/LsbfLmc1/

Hope this can help you. You can also read about the events option here on the docs: 
http://swisnl.github.io/jQuery-contextMenu/docs/items.html#events

**Comment by bbrala** [comment]
Thanks @RareDevil. Does this help you fix you issue @anna647?

**Comment by bbrala** [comment]
Closing this issue for now. if you have any more questions, just reopen it.

**Comment by anna647** [comment]
Thanks!
