### ISSUE TITLE
Specify font awesome icon class

### ISSUE THREAD

**Issue by Hemanth089** [swisnl/jQuery-contextMenu#328]
Hi, 

Can you add new feature to specify font awesome icon class to display icons?

http://fontawesome.io/icons/

**Comment by bbrala** [comment]
For now i'd advise to add the icons yourself. Just pick which icons you want from the SVG in [encharm/Font-Awesome-SVG-PNG](https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg) and follow the [docs for customisation](https://github.com/swisnl/jQuery-contextMenu/blob/master/documentation/docs/customize.md).

**Comment by Hemanth089** [comment]
A minor tweek on jq and css files I made it done. Now I can add font awesome icons to context menu.

**Comment by bbrala** [comment]
Can you share that tweak in a branch so i can have a look?

**Comment by Hemanth089** [comment]
​Compare this with your js and css file.​


--

Thanks & Regards,
*Hemachandhiran Harimoorthy*
Principal software engineer
+91 7200453620

**Comment by bbrala** [comment]
I see no code. :)

**Comment by Hemanth089** [comment]
Sorry, attached the file in email that didn't work out well. Not sure this is work for all. But for me its working fine.

eg of usage:


 $.contextMenu({
                        selector: ".context-menu-selector",
                        items: {
                            "Open": {
                                name: "Open",
                                icon: "fa fa-eye fa-lg fa-fw",
                                callback: function (key, options) {
                                   
                                }
                            }
                        }
                    });

[jquery.contextMenu.zip](https://github.com/swisnl/jQuery-contextMenu/files/73184/jquery.contextMenu.zip)
