### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by rinu** [swisnl/jQuery-contextMenu#333]
How do I use a custom icon in 2.0?
There are no complete examples, no documentation. And I can't figure it out from the source code.
I'm so frustrated already, it's like it's not even possible anymore.

I had a custom icon before but who knows what version I was using. It used to be as simple as adding a single class to my css file pointing to an icon file, done. Now wtf.

I only upgraded because $('el').contextMenu() was not working in the version I was using but I need that now. If that was added before 2.0 can you tell me what version has that and not the new icon system and where can I get it?

**Comment by kevinferrero** [comment]
I ran into the same problem.  I'm not real familiar with the plugin, there is probably a better/easier way... but this worked for me.  https://jsfiddle.net/kevinferrero/2mz7hg5t/

.context-menu-item.context-menu-icon-customicon { padding: 3px 3px; }
.context-menu-item.context-menu-icon-customicon::before {
  content: '';
  display: inline-block;
  width: 15px; height: 15px;
  background-image: url('icon_img.png');
}

**Comment by rinu** [comment]
I see you took the hackish route, as did I.
What I ended up doing was using built-in icons and overwriting the images with png-s.
Built-in icon list includes 'edit', 'delete' and 'quit', among others. I only needed 3, chose those.
I'm not very happy about that content "\1" line since I've no clue how that works. But the content needed to be non-empty, any letter in there would appear on top of the icon and space didn't work.

li.context-menu-icon-edit:before {
	background-image: url(edit.png);
}
li.context-menu-icon-delete:before {
	background-image: url(delete.png);
}
li.context-menu-icon-quit:before {
	background-image: url(custom_icon.png);
}

li.context-menu-item:before {
	content: "\1";
	background-repeat: no-repeat;
	background-position: center center;
}

**Comment by RareDevil** [comment]
@rinu have to been reading on how the icon works here http://swisnl.github.io/jQuery-contextMenu/docs/items.html#icon ?

**Comment by bbrala** [comment]
I'm sorry the documentation is not updated yet, sorry!

For adding custom icons, you can add them to as SVG which makes them available as an option.
https://github.com/swisnl/jQuery-contextMenu/blob/master/documentation/docs/customize.md

I will update the documentation sometime soon.

**Comment by bbrala** [comment]
First iteration of the documentation is now online. http://swisnl.github.io/jQuery-contextMenu/docs/customize.html

The :before{ content:"\xxxx"} is css to add a UTF character before the element. Because of the generated font with the icons this will translate to an icon.

**Comment by rinu** [comment]
Thanks for the effort.
However I don't think you fully understood my issue.
I haven't downloaded the entire project, I'm not developing this extension. I've never run the "gulp" command, nor have I ever drawn SVG.
What I was looking for was a one-liner to get my png image in there. You know, like you could with an older version. My solution seems hackish, I'm not proud of it and I don't like having it in production. But it seems a clean solution doesn't exist for me.

**Comment by bbrala** [comment]
Fair enough. Using an iconfont for icons has been available for quite a while and has a lot of advantages like less requests, limitless scalability, styling with colors/shadows like any font.

You can override the ``:before { content: "" }`` with an empty string i think, which is kinda like clearing it. Its pretty much the only way to do this. 

Again though, i would advise you to have a look into icon-fonts, they are awesome :)

**Comment by rinu** [comment]
Just a couple more things.

My website uses several layouts, the newest one with Flaticon. Yes, icon-fonts are pretty cool but also a pain to work with compared to png files for example.

I see contextMenu as just another library in my code, as such I don't want to touch it in any way. It's just a way of keeping sane when updating libraries later.
Therefore I'm not excited about having to edit the distribution CSS to make Flaticon work in it. It is possible to override and copy-paste every line but that again isn't a good approach. The selector in question is this one
```css
.context-menu-icon-add:before, .context-menu-icon-copy:before, .context-menu-icon-cut:before, .context-menu-icon-delete:before, .context-menu-icon-edit:before, .context-menu-icon-paste:before, .context-menu-icon-quit:before {
    position: absolute;
    top: 50%;
    left: 0;
    width: 28px;
    font-family: context-menu-icons;
...
    -moz-osx-font-smoothing: grayscale;
}
```
Just change the selector to context-menu-item:before and all will be well. When that's done all I need to do in my CSS is overwrite the font-family, content and fix my margins and that's it, Flaticon will then work.
In my JavaScript of course I then change icon from string to function that returns my classes as is documented.

I didn't even remember I had Flaticon there until your most recent comment. Maybe if I had started there I would have ended up with a completely different hackfix :)

**Comment by bbrala** [comment]
Yeah i realize it might not be ideal how things are right now in regards to those icons. I do understand you might now want to change too much to be able to do this. The hard thing is it is hard to keep everyone happy with a solution. 

It might have been more obvious if the generic CSS for the :before statement was in one selector. Maybe it would be nice to have a few examples of integrations of different icon types at some point.

Anyways, glad you found the solution. Hope the library is usefull for you :+1:

**Comment by kevinferrero** [comment]
Very helpful... thanks for the updated docs, I see you did a ton of work around the new icons. they look great.
