### ISSUE TITLE
Incorrect entry on package.json

### ISSUE THREAD

**Issue by Dijir** [swisnl/jQuery-contextMenu#336]
Hello,

I'm trying to install using jquery 2.1.4 but I got the following error:
`npm ERR! peerinvalid The package jquery@2.1.4 does not satisfy its siblings' peerDependencies requirements!`
`npm ERR! peerinvalid Peer jquery-contextmenu@1.10.3 wants jquery@^1.8.2`

On package.json at peerDependencies entry jquery is specified with ^1.8.2, this will match just >= 1.8.2 and  <= 1.9.9.

I ask you to change to:
`  "peerDependencies": {`
`    "jquery": ">=1.8.2"`
`  }`

So it will be compatible with recent jquery versions.

Thanks.

**Comment by bbrala** [comment]
Thanks for the heads up, i changed the package.json
