### ISSUE TITLE
Show multiple hovered rows

### ISSUE THREAD

**Issue by sashamee** [swisnl/jQuery-contextMenu#346]
I took your example of nested menus, and move the mouse from parent menu to a child menu. I got two selected rows in the same time. I got the same bug in production.
image attached
![context-menu-bug](https://cloud.githubusercontent.com/assets/11330440/12882308/619482fa-ce59-11e5-8c95-9986dfe236c7.png)

**Comment by bbrala** [comment]
Thanks for reporting, that is pretty weird.

**Comment by bbrala** [comment]
Can't reproduce this anymore :)
