### ISSUE TITLE
Auto hide issue with IE 11

### ISSUE THREAD

**Issue by Risord** [swisnl/jQuery-contextMenu#347]
Hi

If you move mouse too quickly over submenu in IE 11, auto hide will close menu immediadly. This can be replicated in demo: https://swisnl.github.io/jQuery-contextMenu/demo/trigger-hover-autohide.html 

Note that in case where menu and hover trigger are overlapping this issue is related to mouse move speed / mouse move event frequency. This is caused by fact that if you move your mouse over menu and outside hover trigger in IE mousemove.contextMenuAutoHide event will fire before mouse enter event and opt.hovering is not correctly set to true.

Simple fix:

`if (opt.$layer && !opt.hovering && (!(e.pageX >= pos.left && e.pageX <= pos.right) || !(e.pageY >= pos.top && e.pageY <= pos.bottom))) {
  /*Additional hover check after short time*/
  setTimeout(function () {
  if (!opt.hovering) {
    opt.$menu.trigger('contextmenu:hide');
  }
  }, 1);
}`

**Comment by bbrala** [comment]
Thanks, that seems like a proper bug, will have a look soon :+1:
