### ISSUE TITLE
Invisible items not skipped when using up and down arrows

### ISSUE THREAD

**Issue by arashdalir** [swisnl/jQuery-contextMenu#348]
It seems like the menu items which are marked as invisible (visible: false) are still counted when the up and down buttons are used to control the menu. If there is an invisible item (#2) between two visible items(#1 and #3), the focus goes from #1 to #2 (display:none) to #3.

**Comment by arashdalir** [comment]
so, this problem has been fixed in 8e18de4c28dc15ffec895f093c777b3565d66ed3. Thanks :)

**Comment by bbrala** [comment]
Hehe sorry forgot to comment here. Yeah I made a fix but need to check if nothing breaks since a test is falling. I was called away from my computer.
