### ISSUE TITLE
Pressing down key won't work when first item has type=html 

### ISSUE THREAD

**Issue by arashdalir** [swisnl/jQuery-contextMenu#349]
The following context menu is not operable with only down key. If no item has focus or the items' list reaches its end, the down key should start at the beginning and set focus to the first item in the list, but it cannot. My guess is, because the first item is an HTML item (maybe I'm defining the item in a wrong manner) and the default className is not assigned to it, the key events are not triggered as expected.
```
$.contextMenu({
	selector: '.context_menu',
	items: {
		'title': {
			type: 'html',
			icon: function (options, $itemElement, key, item)
			{
				$itemElement.html('<h2>Actions</h2>');
			}
		},
		'sep1': '-----------------',
		'details': {
		name: 'Details',
			icon: 'details'
		},
		'save': {
			name: 'Save',
			icon: 'save'
		}
	}
});
```

**Comment by bbrala** [comment]
I tried to reproduce this on my local master, but wasn't able to. Do you see it when you use the current master branch of the library?

**Comment by arashdalir** [comment]
I'll check this on Monday and report back.

**Comment by bbrala** [comment]
Ok thanks :)

**Comment by arashdalir** [comment]
Hi,
This problem still exists in the newest revision. 

You can reproduce is using the following code and by following the mentioned steps:

1. right click on menu and open it
2. press "Down" arrow key. Expected: first item (Details) should have focus. Outcome: well, nothing. 

I checked the DOM changes using chrome-developer bar, and when clicking down button, the first <li>, which contains the header (HTML element) gets highlighted, indicating that the JS is probably changing some of its properties, but nothing happens. Probably wrong selector or something?

If it's needed, I can investigate the issue in a deeper level (well, I mean not just as a dummy end-user :D )

Thanks.

test code:
```
<!DOCTYPE HTML>
<html>
<head>
	<link href="../themes/standard/css/jquery.contextMenu.css" rel="stylesheet" />
</head>
<body>
<script type="text/javascript" src="../scripts/jquery-1.8.3.js"></script>
<script type="text/javascript" src="../scripts/jquery-ui-1.9.2.custom.min.js"></script>
<script type="text/javascript" src="../scripts/jquery.contextMenu.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		$.contextMenu({
			selector: '.context_menu',
			items: {
				'title': {
					type: 'html',
					icon: function (options, $itemElement, key, item)
					{
						$itemElement.html('<h2>Actions</h2>');
					}
				},
				'sep1': '-----------------',
				'details': {
					name: 'Details',
					icon: 'details'
				},
				'save': {
					name: 'Save',
					icon: 'save'
				}
			}
		});
	})
</script>
<div class="context_menu">Testing CM</div>
</body>
</html>
```


created html:
```
<ul class="context-menu-list context-menu-root" style="width: 213px; top: 8px; left: 27px; z-index: 1; display: none;">
<li class=""><h2>Actions</h2></li>
<li class="context-menu-item context-menu-separator context-menu-not-selectable"></li>
<li class="context-menu-item context-menu-icon context-menu-icon-details"><span>Details</span></li>
<li class="context-menu-item context-menu-icon context-menu-icon-save context-menu-visible"><span>Save</span></li>
</ul>
```

**Comment by bbrala** [comment]
When i use the same items on the current master branch (src version) i get the following HTML for the h2, which works fine:

```<li class="context-menu-item context-menu-html context-menu-not-selectable"><h2>Actions</h2></li>```

**Comment by arashdalir** [comment]
Thanks a lot, as you mentioned the issue is resolved :)
