### ISSUE TITLE
Calling .contextMenu('hide') throws an error

### ISSUE THREAD

**Issue by arashdalir** [swisnl/jQuery-contextMenu#351]
Hi again!

Apparently manually firing the .contextMenu('hide') function to manually hide the menu causes the following line to trigger an exception. The root.$menu is empty when function is triggered manually (i.e. JS function $menu.contextMenu('hide')). When tracing the js-code, the value is filled if event is triggered when user clicks away, but not when js fires the function.

line:636: `root.$menu.trigger('contextmenu:hide');`
result: `Uncaught TypeError: Cannot read property 'trigger' of undefined`

**Comment by bbrala** [comment]
Good catch, kind of weird. I'll try to make some time this week to go through this issue.

**Comment by arashdalir** [comment]
Well, I'm (ab)using the menu really strongly and therefore find some things, which aren't seen easily! :D 
I'm not sure if I can also ask for a feature-implementation, I should do it in a separate issue, right?

**Comment by bbrala** [comment]
The easiest way to get a feature in is to open a issue to discuss and then make a pull request. But i do try to create features that i feel are good additions. The problem is my time is sometimes a little limited :)

**Comment by arashdalir** [comment]
Could you please inform me if this feature is already implemented or not?
Is there a way to see if the contextmenu ist open at any point of time? If it's not implemented, I'll make an issue (feature request) out of it.

Thanks a lot

**Comment by bbrala** [comment]
I searched the repos and found the clicked element gets a classname: ``context-menu-active``, see https://github.com/medialize/jQuery-contextMenu/issues/92

**Comment by arashdalir** [comment]
Thanks a lot :) You are right, I could have checked that. 
Sorry and Thanks again

**Comment by bbrala** [comment]
Seems fixed see #352
