### ISSUE TITLE
Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by andreasrosdal** [swisnl/jQuery-contextMenu#352]
[Freeciv-web](https://github.com/freeciv/freeciv-web) uses jQuery contextMenu v2.1.0 to show the context menu. We use a JavaScript error logging-tool called Track:js, which has reported these JavaScript errors in contextMenu.

Reported 897 times by Track:js:
![trackjs-1](https://cloud.githubusercontent.com/assets/210993/13122350/c6a93c6c-d5b6-11e5-9e43-6d187aae3a16.png)

Reported 283 times:
![trackjs-2](https://cloud.githubusercontent.com/assets/210993/13122352/c8e9785c-d5b6-11e5-8d9d-dded4b1f5004.png)

Any help in resolving these?

**Comment by andreasrosdal** [comment]
This seems related to bug #351.

**Comment by bbrala** [comment]
Thanks for reporting this, i'll try and make time this week to go through this issue.

**Comment by jasekiw** [comment]
I also have ran into this problem. It seems to only happen when using anonymous callbacks in the same scope. A work around is to set a variable to trigger and then use that instead.

`var target = opt.$trigger;`

**Comment by bbrala** [comment]
@jasekiw Do you mean on the items? I've been trying to reproduce this problem, but i can't really at the moment. Do you have a configuration that breaks for me?
