### ISSUE TITLE
Dynamic item name

### ISSUE THREAD

**Issue by ray73864** [swisnl/jQuery-contextMenu#356]
Is it possible to dynamically change the name when you right click on an item and the menu appears?

I have a series of rows in a table, if a person right clicks on 1 row I would like the name of some of the menu items to change, for example I might have a menu item that says 'Delete Row' and I might like it to actually say 'Delete Row: <description from one of the tds in the table>' (eg: "Delete Row: Freds Service Centre").

**Comment by bbrala** [comment]
You can use the [build](https://swisnl.github.io/jQuery-contextMenu/docs.html#build) option to build the menu on runtime, then you can access some information of the clicked item to change the item title if you like.

**Comment by ray73864** [comment]
Ahh nice, thankyou for that. 

I am running 1.6.5, looks like I shall have to update too, just so that I have bug fixes, etc...
