### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by ray73864** [swisnl/jQuery-contextMenu#357]
Is there a possibility of grouping like menu items with a title for each group? At present one can do a seperator, but I would like to be able to seperate each group by a non-clickable title.

Or, is it better to just create a non-clickable item?

**Comment by bbrala** [comment]
The documented wat to add a new type (a title) is https://swisnl.github.io/jQuery-contextMenu/docs/custom-command-types.html

But i've also seen code like this to do pretty much the same.

```
               'title': {
                    type: 'html',
                    icon: function (options, $itemElement, key, item)
                    {
                        $itemElement.html('<h2>Actions</h2>');
                    }
                },
```
