### ISSUE TITLE
right click with server side call or Ajax enabled

### ISSUE THREAD

**Issue by patagoniahiker** [swisnl/jQuery-contextMenu#366]
Hi, I am trying your plugin its very nice :+1: 

I was looking for a sample to trigger different server side functions for e.g. 2 or 3 Ajax calls based on selection argument/value - can you please include something where the user can right click (and send the value with content to the server)

For e.g. user rightclicks **Save**-> prompt then -> _action SaveCall + data=SaveJsonRecord_ and refresh

thanks

**Comment by bbrala** [comment]
Wouldn't a [callback](http://swisnl.github.io/jQuery-contextMenu/docs/items.html#callback) with a prompt suffice? I'm not entirely sure what you try to accomplish

**Comment by patagoniahiker** [comment]
thanks.. yes, but I thought it would simplified... for e.g. a simplified format that could take the div/cell context + menu item and pass it through the same function
