### ISSUE TITLE
How to pass dynamic parameters  In callback section

### ISSUE THREAD

**Issue by ajaybairagi** [swisnl/jQuery-contextMenu#367]
Hello,

I am calling  contextMenu with function and pass EventId. EventId  proper Alert but in  callback EventId alert wrong.
see below code. Have any option to get dynamic EventId in callback section.
function myContextMenu(EventId){
	var EventId;
alert(EventId);
	$.contextMenu({
						selector: '.fc-event-container', 
						callback: function(key, options) {
							//var m = "clicked: " + key;
							//window.console && console.log(m) || alert(m); 
							 
							alert(EventId);
						},
						items: {
							"edit": {name:'Edit', icon: "edit"},
							"cut": {name: "Cut", icon: "cut"},
							"copy": {name: "Copy", icon: "copy"},
							"paste": {name: "Paste", icon: "paste"},
							"delete": {name: "Delete", icon: "delete"},
							"sep1": "---------",
							"quit": {name: "Quit", icon: function(){
								return 'context-menu-icon context-menu-icon-quit';
							}}
						}
					});
					
 		
	}

**Comment by bbrala** [comment]
This is a scoping issue i think. When you first call the function the EventId variable is initialized and the context menu is initialized. The next time the function is called the variable is only set for that scope. I think the contextmenu is not initilized again from scratch. 

One wat to fix this is to have the Event ID somewhere in the global scope. So `var EventId;` outside the function.

A nicer wat would be to add a data attribute to the the `.fc-event-container` and read that in the [callback from the trigger element](http://swisnl.github.io/jQuery-contextMenu/docs/items.html#callback).
