### ISSUE TITLE
How can get items with json

### ISSUE THREAD

**Issue by ajaybairagi** [swisnl/jQuery-contextMenu#368]
Hello,
How can I replace items: {  } to json data.
because I want to generate menu  items with dynamically. 

$(function() {
        $.contextMenu({
            selector: '.context-menu-one', 
            callback: function(key, options) {
                var m = "clicked: " + key;
                window.console && console.log(m) || alert(m); 
            },
            items: {
                "edit": {name: "Edit", icon: "edit"},
                "cut": {name: "Cut", icon: "cut"},
                 copy: {name: "Copy", icon: "copy"},
                "paste": {name: "Paste", icon: "paste"},
                "delete": {name: "Delete", icon: "delete"},
                "sep1": "---------",
                "quit": {name: "Quit", icon: function(){
                    return 'context-menu-icon context-menu-icon-quit';
                }}
            }
        });

        $('.context-menu-one').on('click', function(e){
            console.log('clicked', this);
        })    
    });

**Comment by bbrala** [comment]
I think you mean to build the menu dynamicly? If so, use the [build](https://swisnl.github.io/jQuery-contextMenu/docs.html#build) option.
