### ISSUE TITLE
Allow html name

### ISSUE THREAD

**Issue by zendre4** [swisnl/jQuery-contextMenu#369]
Hello,
Since 2.0 version if we defined an item with a name wich contain html, the html tags was not interpreted.

Exemple:

if we define name like this : `&eacute;t&eacute;` , the generate name is `&eacute;&eacute;`  not été.

For fix it I change the function "createNameNode" on ligne 1078, I replace ".text(...)" by ".html(...)" 

```
function createNameNode(item) {
    var $name = $('<span></span>');
    if (item._accesskey) {
        if (item._beforeAccesskey) {
            $name.append(document.createTextNode(item._beforeAccesskey));
        }
        $('<span></span>')
            .addClass('context-menu-accesskey')
            .html(item._accesskey)
            .appendTo($name);
        if (item._afterAccesskey) {
            $name.append(document.createTextNode(item._afterAccesskey));
        }
    } else {
        $name.html(item.name);
    }
    return $name;
}
```

**Comment by bbrala** [comment]
This was kind of discussed in issue #252, but i rather not implement it in such a magic way, i would rather see a seperate way to allow HTML in the same. If you have suggestions please place them in issue #302
