### ISSUE TITLE
Complex access keys

### ISSUE THREAD

**Issue by Bob0t** [swisnl/jQuery-contextMenu#372]
Hey,

I would like to use complex access keys, like the Delete key of the keyboard, or things like SHIFT + A etc ..

I did not found any help on google or in the issues about it. (q= access keys)

Is there a way to use them in this version of contextMenu or some "hacks" to do it ?

**Comment by bbrala** [comment]
I'm not sure about this. I think the spec doesn't allow for acceskeys with keys like delete. I've used [jquery.hotkeys](https://github.com/jeresig/jquery.hotkeys) in some projects with some success. But those would be global.

In our CMS we use this to capture things like delete and ctrl+s where it is possible to give easy shortcuts. But that really has nothing to do with the contextmenu.
