### ISSUE TITLE
Radio button group lack of click event or callback after click?

### ISSUE THREAD

**Issue by msqar** [swisnl/jQuery-contextMenu#373]
I'm trying to get a callback or something after clicking on a radio button group, but seems to be missing. How can I accomplish this? Is it possible?

Thanks

**Comment by bbrala** [comment]
Hmm, you can use the [events](https://swisnl.github.io/jQuery-contextMenu/docs/items.html#events) on the item, this should enable you to put a click or change event on the checkbox.

**Comment by msqar** [comment]
Well... that's the first thing i tried. For all other dom elements worked... but for radio buttons didn't. That's why I created this post.
Tried adding on the radiobutton item:

```
// this is a submenu
"settings": {
                "name": "Settings",
                "items" : {
                    "auto" : {
                        "name" : "Auto",
                        "type" : "radio",
                        "radio" : "settingsRadio",
                        "value" : "auto"
                    },
                    "on" : {
                        "name" : "On",
                        "type" : "radio",
                        "radio" : "settingsRadio",
                        "value" : "on"
                    },
                    "off" : {
                        "name" : "Off",
                        "type" : "radio",
                        "radio" : "settingsRadio",
                        "value" : "off"
                    },
                    "events": { // <-- here didn't work
                             "click" : ...
                    }                    
                },
                "events": { // <-- here didn't work either
                  "click" : ...
                }       
            },
```

So after posting in Stackoverflow, i had to do this:

`$(document).on("change", ".context-menu-item input[type='radio']", function (e) {`

Didn't like it but that's the only way i made it work.

**Comment by bbrala** [comment]
The event object should be inside the radio item I think. Could you try that?
