### ISSUE TITLE
The show animation does not work

### ISSUE THREAD

**Issue by alihb2005** [swisnl/jQuery-contextMenu#376]
show animation does not work even with default options

**Comment by alihb2005** [comment]
The problem is in the "show" function
Before the animation, a call to the "update" function makes it visible by setting the "display" property to "block"
So I made the "display" property to "none" before the animation plays and problem solved

**Comment by bbrala** [comment]
In order to get this properly working we need to rework animations. Don't think we'll be doing that any time soon. Sorry.
