### ISSUE TITLE
In Meteor, $.contextMenu is not a function

### ISSUE THREAD

**Issue by sedacire** [swisnl/jQuery-contextMenu#377]
We use contextMenu in our application. It was working very well in Meteor prior version 1.3.

But with the update of Meteor to version 1.3, $.contextMenu is not a function.

**Comment by bbrala** [comment]
Personally I have never used meteor, any idea what broke? Could you compose a test case maybe?

**Comment by sedacire** [comment]
Ok, I will try with this:
------------------------------------------------------------------
Install Meteor : https://www.meteor.com/install

Create a project:

meteor create test
cd test
meteor npm install --save jquery jquery-contextmenu
meteor

it's on localhost:3000

Modify main.js and main.html to use contextMenu
-----------------------------------------------------------------------

Maybe it's a matter of import or require contextMenu...

**Comment by sedacire** [comment]
Before I was copying the dist folder of contextMenu in the client folder of meteor and everything was ok. But with the update of Meteor, now it's not.

So, Meteor new philosophy is to use "meteor npm install" to use of node modules. Not atmosphere.js modules anymore.

**Comment by sedacire** [comment]
I found that I have to import my node modules at the top of my JS file. So:

import $ from 'jquery';
import contextMenu from 'jquery-contextmenu'

$(function(){
	$.contextMenu({
	    selector: ".test",
	    items: {
	    	foo: {name: "Foo", callback: function(key, opt){ alert("Foo!"); }},
        	bar: {name: "Bar", callback: function(key, opt){ alert("Bar!") }}
	    },
	});
});


But how do I include the CSS file from the node_modules ?

**Comment by bbrala** [comment]
Glad you found a way to fix this and shared it here. :+1:
