### ISSUE TITLE
Menu not closing when clicking elements which are absolute or fixed positioned. 

### ISSUE THREAD

**Issue by riqwan** [swisnl/jQuery-contextMenu#378]
The context menu doesn't close when you click on any elements that are positioned absolute or fixed. 

You can see an example on the demo page itself - [Demo Page](https://swisnl.github.io/jQuery-contextMenu/demo.html)

1. Right click on the "Right Click me" button to open up the context menu
2. Click on the left sidebar element.

**Comment by riqwan** [comment]
Oh never mind, i looked it up in the code and figured it out.

Note: (Just in case anyone else is wondering)

The z-index of the context menu layer (`#context-menu-layer`) should be greater than the z-index of the element that is being clicked on for the context menu hide to occur.

**Comment by bbrala** [comment]
Thanks for the report and solution :)
