### ISSUE TITLE
build-icons character set on windows

### ISSUE THREAD

**Issue by roselan** [swisnl/jQuery-contextMenu#380]
when I build icons on a windows machine, all icons are displayed the "missing char in font" " empty box.

What a tried: 
* build icons
* get svg icons from the svg-pgn-font-wesome rep, build icons
* got all gulp deps, and gulped full project.
* got original woff, eot etc font files from the font-awsom rep, and tried to hack them in contextMenu.

No strawberry.

I did notice that in the sassed css, icon characters do not correspond to the original when i build it through gulp. By example, "delete" icon character becomes "EE A8 84" instead of "EE AA BC".

I'm on a windows machine, and I found a gulp issue that might explain the behavior:

I pointed it to the gulp team too: https://github.com/gulpjs/gulp/issues/1546#issuecomment-207314603

**Comment by bbrala** [comment]
Hmm, weird, i've had no issues, but i build on Linux. To make things a little more visible i made a branch where the icon character is a readable string in commit e0b8f7d3e563f5073d7db1c526ae4ba51e10d5dd.

**Comment by roselan** [comment]
Thank you. 

That's exactly what I did (well, nearly, i added the backslash directly:` "\<%= glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase() %>"`)

But that didn't work as expect. by example: you generate 
```
.context-menu-icon-delete:before {
  content: "\EA04";
}

```
and I generate:
```
.context-menu-icon-delete:before {
  content: "\EABC";
}
```

**However**. That's with all svg fonts from https://github.com/encharm/Font-Awesome-SVG-PNG.

When I build-icons with only the ones you provided, it works!

both your and and encharm delete.svg files are strictly equals.

I'm quite certain the fault is on me, it's my first time using npm/gulp. Please note that when I build, i get the 4 warning, and have to interrupt it (but it works). I did copy all encharm icons inside the "icon" folder and ran:

```
C:\projects\jQuery-contextMenu-master>gulp build-icons
[19:42:36] Using gulpfile C:\projects\jQuery-contextMenu-master\gulpfile.js
[19:42:36] Starting 'build-icons'...
[19:42:37] Finished 'build-icons' after 680 ms
[19:42:37] gulp-svgicons2svgfont: Font created

C:\projects\jQuery-contextMenu-master>gulp
[19:42:47] Using gulpfile C:\projects\jQuery-contextMenu-master\gulpfile.js
[19:42:47] Starting 'jshint'...
[19:42:47] Starting 'jscs'...
[19:42:48] Starting 'jslibs'...
[19:42:48] Starting 'css'...
[19:42:49] Finished 'jslibs' after 503 ms
src\jquery.contextMenu.js: line 916, col 9, 'op' was used before it was defined.

src\jquery.contextMenu.js: line 1123, col 56, Expected a conditional expression
and instead saw an assignment.
src\jquery.contextMenu.js: line 1398, col 14, 'splitAccesskey' was used before i
t was defined.
src\jquery.contextMenu.js: line 1402, col 36, Expected a conditional expression
and instead saw an assignment.

4 errors
[19:42:49] Finished 'jshint' after 2.6 s
[19:42:51] Finished 'jscs' after 3.38 s
[19:42:51] Starting 'js'...
[19:42:51] Finished 'css' after 3.14 s
[19:42:51] Finished 'js' after 941 ms
[19:42:51] Starting 'watch'...
[19:42:51] Finished 'watch' after 19 ms
[19:42:51] Starting 'default'...
[19:42:51] Finished 'default' after 11 µs
^CTerminate batch job (Y/N)?
Terminate batch job (Y/N)? y

C:\projects\jQuery-contextMenu-master>
```

Ok, after running it again with both your and all icons, I noticed that the .woff2 file is not created -.-'''. It might be linked to https://github.com/nfroidure/gulp-iconfont/issues/64. Anyway by adding 
`
			, formats: ['ttf', 'eot', 'woff', 'woff2']

`
to iconfont options, it works :+1: (pls check my pull request)

I'm not sure what exact part, or combination of them, was the culprit, and honestly I don't have the time to investigate. Your branch + forcing woff2. 

Finally, I want to thank you for your effort for maintaining this plugin we use since before it was versioned (aka 2011-12), and never ever updated until today. It now is really great.
