### ISSUE TITLE
Make CSS units scalable

### ISSUE THREAD

**Issue by xfactor5** [swisnl/jQuery-contextMenu#386]
Hi,
All over the CSS "px" is used as the unit. If it's converted to "em", then the menu will easily adapt itself with the sizing of the whole document, it's looks will be more consistent and the developer will be allowed to scale the menu as much as he wants it (without having to change so many parameters like paddings and margins).
Thanks

**Comment by bbrala** [comment]
This seems like a good point, i'll ask my college if he sees problems in doing this.

**Comment by RoachMech** [comment]
I've made a pull-request with all ems for units. #389

**Comment by bbrala** [comment]
Fixed
