### ISSUE TITLE
An item should remain highlighted as long as its associated submenu is being displayed

### ISSUE THREAD

**Issue by xiatianyu** [swisnl/jQuery-contextMenu#387]
As can be observed from the screenshot below, while the submenu is still being displayed, the menu item _turtle 32_ becomes unhighlighted. I suspect this is because an `contextmenu:blur` event was triggered on _turtle 32_ when the mouse moved outside. This is not the normal behaviour for context menus and thus should be fixed.

![screenshot from 2016-04-11 12-02-23](https://cloud.githubusercontent.com/assets/11317451/14416556/fd6e593e-ffdd-11e5-96c6-38f1ce0c24da.png)

**Steps to reproduce this behaviour:**
1. Create and trigger a context menu with a submenu.
2. Expand the submenu by hovering the mouse over the menu item with which the submenu is associated.
3. Move the mouse out of the menu without moving into the submenu or any other menu items.

**Comment by bbrala** [comment]
I see what you mean. if the menu is a submenu it shouldn't unhighlight until submenu is closed. Thanks for the report. Can you tell me what version you use?

**Comment by xiatianyu** [comment]
@bbrala I'm using v2.1.0. Note the behaviour in question can also be observed in the [submenu demo](https://swisnl.github.io/jQuery-contextMenu/demo/sub-menus.html).

![screenshot from 2016-04-11 21-03-18](https://cloud.githubusercontent.com/assets/11317451/14428140/5fe0f7ec-002a-11e6-89d4-c638c20f74df.png)
This is how it should always look like.

![screenshot from 2016-04-11 21-03-39](https://cloud.githubusercontent.com/assets/11317451/14428158/74484bcc-002a-11e6-8cdf-f97fb599f9b7.png)
However, this is how it looks like if the steps above are followed.

**Comment by bbrala** [comment]
I've tweaked positioning a bit to make this harder. Don't really want to do extra checks in the menu itself for this.
