### ISSUE TITLE
Use of mouseup to handle item click

### ISSUE THREAD

**Issue by CaselIT** [swisnl/jQuery-contextMenu#393]
Is there a particular reason for registering to `mouseup` instead of `click` to handle the click event on the contextMenu [here](https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L1524) ?

This can cause a problem when using a click handler to load the context menu, because an item can be clicked immediately, as in this [live example](http://plnkr.co/edit/IsQH5fTOfI8ExGBMBATd?p=preview) where the issue is exaggerated by loading the menu under the mouse pointer.
Changing the event registered to `click.contextMenu` seems to stop this behaviour from occurring.

**Comment by CaselIT** [comment]
Any update? Thanks

**Comment by bbrala** [comment]
Sorry, was a bit busy. I don't have an awnser of the top of my head. I'll need to double check the history of that piece of code to see what the reason is. I feel it wasn't without reason,

**Comment by CaselIT** [comment]
Great thanks. 
Just wondering, if I make a pull request adding the ability to configure which event to register to handle the click, leaving the `mouseup` event as default, would you be open to accept it?
I'm want to use this library in a project, but this issue is causing me some problems, and I would prefer not to maintain my local copy of the library.

**Comment by bbrala** [comment]
Yeah i would be open to merge such feature. We just need to make sure it doesn't break anything else. Did you try and run the tests with your local changes? I know the framework is pretty old which makes installing sometimes a bit of a hassle so i could check for you if you have the raw modified js.

**Comment by CaselIT** [comment]
I have not jet run the package tests with the changed event handler. I'll try to run the tests to see if everything works. Thanks for the support!

**Comment by CaselIT** [comment]
I've [forked the repo](https://github.com/CaselIT/jQuery-contextMenu) and [added the option](https://github.com/CaselIT/jQuery-contextMenu/commit/9257663b5ebb02bf168220ee79f20a8a9d5aebbb) to change the event that triggers the item click. At the moment it is named `itemClickEvent`, but it's just a temp name until a better one can be found.
The [updated plnkr](http://plnkr.co/edit/SbeIlHZMYMbachkaikjY?p=preview)

I've added the quint test for the feature also, duplicating the existing ones. [Travis build is here](https://travis-ci.org/CaselIT/jQuery-contextMenu/builds/132044548) 
I'm not sure how to proceed with the integration tests, since I'm not sure duplicating all of them is the best strategy

**Comment by bbrala** [comment]
Thanks! I'll have a look soon

**Comment by bbrala** [comment]
I've had a look and it indeed seems fine this way. It just needs an entry for that option in the docs and a PR and i'll merge this. :)

Note, this might also be the better option for PR #379

**Comment by bbrala** [comment]
Might also fix #332

**Comment by CaselIT** [comment]
This evening I think I'll have the time to do the PR.
I'll leave the option named as is, and add it to the docs.
Two observation:
* As it is now the option is global: only the first contexMenu can change it since afterwards [`initialized ` is set](https://github.com/swisnl/jQuery-contextMenu/blob/d685eea23270110568181c3031d82eba23272f73/src/jquery.contextMenu.js#L1534) so no change can happen until all the context menu are destroyed and [the flag is reset](https://github.com/swisnl/jQuery-contextMenu/blob/d685eea23270110568181c3031d82eba23272f73/src/jquery.contextMenu.js#L1612). Do you think this behaviour is acceptable? Also is it possible to set it for a specific contex menu? (Maybe registering to both event and moving the check inside the handler to only allow the selected one)
* I've not added the integration test, I can see if I can add some if needed

**Comment by bbrala** [comment]
Glad to hear!

I wouldn't mind it being global. And don't bother with the integration tests. The framework that is currently in use is old and no longer updated. Haven't had the chance to figure out what to use instead or to just expand the unit tests.
