### ISSUE TITLE
Error on try to recreate menu after destroy

### ISSUE THREAD

**Issue by punk2x** [swisnl/jQuery-contextMenu#397]
When try to recreate menu on same selector, after destroy, causes the following error:

`Uncaught TypeError: Cannot read property 'disabled' of undefined`

your code:

`disabled = ($.isFunction(item.disabled) && item.disabled.call($trigger, key, root)) || item.disabled === true,`

On `case 'destroy':` ... `if (o.context !== context)` Is always false, and don't destroy anything. Removing this validation, all works.

My "destroy" code:
`$(".my-context").contextMenu("destroy");`

Tested on google chrome (50.0).

**Comment by bbrala** [comment]
Refactored the context part to something more sane. Should be fixed in master now.
