### ISSUE TITLE
toggle contextMenu on inputSelector

### ISSUE THREAD

**Issue by collmomo** [swisnl/jQuery-contextMenu#398]
```
 $.contextMenu({
                selector: 'input.test',
                trigger: 'left',
                callback: function (key, options) {
                      //do stuff
                },
                items: it
            });
```

The input is disabled and there is a hover css on it. I'm not sure to understand why this won't work.

**Comment by bbrala** [comment]
Can you put the relevant code on jsfiddle?

**Comment by collmomo** [comment]
https://jsfiddle.net/cb6urLcf/3/

**Comment by bbrala** [comment]
Thank you for the fiddle, the thing is, browsers disable all click events on disabled inputs, so there is not much possible. A way to get around this is using css or a container div.

http://stackoverflow.com/questions/3100319/event-on-a-disabled-input
