### ISSUE TITLE
"Open afer Click" keeps incressing the menu width.

### ISSUE THREAD

**Issue by aadrian** [swisnl/jQuery-contextMenu#402]
Clicking "open after click" in this example:
https://swisnl.github.io/jQuery-contextMenu/demo/keeping-contextmenu-open.html
will increase the menu width.

Clicking several times, keeps the menu width increasing.

**Comment by bbrala** [comment]
Yeah, this is slightly anooying but not really critical. Thanks for the report :)

**Comment by bbrala** [comment]
Sorry won't be fixing this :)
