### ISSUE TITLE
Wrong style while hovering over item with item commands

### ISSUE THREAD

**Issue by pleskankaj** [swisnl/jQuery-contextMenu#405]
Hi,
If i make some item with type="text" for example and hover it, text will become white and back color is light gray so its almost unreadable. Here is [fiddle](http://jsfiddle.net/c46ynmhe/2/). Script in fiddle is maybe older version, but i have same result on newest version.
Thx

**Comment by bbrala** [comment]
Hmm, good catch. Seems the hover hover class has color now, but this was not corrected in the hover-input.
