### ISSUE TITLE
Trying to add context menu to certain parts of nested ul

### ISSUE THREAD

**Issue by barbmc** [swisnl/jQuery-contextMenu#406]
I have a menu like this

`<ul class="utop">
       <li>
            <ul>
                   <li></li>
                   <li></li>
           </ul>
      </li>
</ul>`

I want to attach my context menu to only the top level li so I have set the selector as 

selector: "ul.utop > li"

However the context menu shows up on every element of the menu. Am I doing something wrong?

**Comment by bbrala** [comment]
My first guess would be the event propegates thought to the lower element. But you could give the first level of li's a class to confirm this.

**Comment by bbrala** [comment]
You could also use the [build](http://swisnl.github.io/jQuery-contextMenu/docs.html#build) option to build the menu based on what triggered the menu.

But still, the behaviour is kinda weird, and wrong.

**Comment by barbmc** [comment]
I tried the build option but it also triggers on second level li'sDate: Sat, 11 Jun 2016 06:59:05 -0700

**Comment by bbrala** [comment]
Yeah you could just return false if the element is not what you need. But that really is a workaround though :)

**Comment by bbrala** [comment]
Can you send me a jsfiddle or a html file with a working demonstration of the issue? I really feal it should be a problem regarding the propegation of the event.
