### ISSUE TITLE
jQuery 3 breaks

### ISSUE THREAD

**Issue by bbrala** [swisnl/jQuery-contextMenu#407]
When running the tests against jQuery 3, the build seems to break.

https://travis-ci.org/swisnl/jQuery-contextMenu/jobs/137253217

global code@/home/travis/build/swisnl/jQuery-contextMenu/test/unit/test-events.js:146:10: undefined is not a function (evaluating 'elem.getClientRects()')

**Comment by PaulOst** [comment]
Broken for me with JQuery 3 as well.

**Comment by bbrala** [comment]
Yeah, i'm going to try and make some time tonight to try and fix jQuery 3, seems relatively straightforward.

**Comment by bbrala** [comment]
Well, looked into it, and it seems the only problem is the jQuery UI position plugin which doesn't support jQuery 3, the new version does, but the download is kind of broken at the moment.

@PaulOst could you check if things are ok for you if you do not include the jquery.ui.position.js?
