### ISSUE TITLE
Downloadable font: Layout: tags aren't arranged alphabetically.

### ISSUE THREAD

**Issue by nelson6e65** [swisnl/jQuery-contextMenu#410]
I get this warning in Firefox on rclick on button for menu (in [documentation  demo](https://swisnl.github.io/jQuery-contextMenu/demo.html)).

 
`downloadable font: Layout: tags aren't arranged alphabetically. (font-family: "context-menu-icons" style:normal weight:normal stretch:normal src index:1) source: https://swisnl.github.io/jQuery-contextMenu/dist/font/context-menu-icons.woff2?1rzc4` in `jquery.contextMenu.css:17:12`.

Apparently not any issue on icons, just noticed and I don't know what that means.  :sweat_smile:

**Comment by bbrala** [comment]
I dont see that warning, appearantly you experience no issues :)
