### ISSUE TITLE
Use 'cm_separator' instead of (or alias for) 'cm_seperator'.

### ISSUE THREAD

**Issue by nelson6e65** [swisnl/jQuery-contextMenu#411]
I just noticed, idk if a typo or intended the usage of 'cm_sep**e**rator' in the code in type for separators (Should not be 'cm_sep**a**rator'?).

Anyway, there should be an alias for more semantic usage: 
```js
{ type: 'cm_separator' }
```

I think is not hard to add it. :+1:

**Comment by nelson6e65** [comment]
Actually... Why not using `'separator'` directly?

**Comment by bbrala** [comment]
Thanks for the contribution!

Scary part of doing that it is a real word. Which might conflict with menu's out there.

**Comment by bbrala** [comment]
Merged and updated documentation

**Comment by 0xorial** [comment]
I do not see any mention of 'separator' in the [docs](http://swisnl.github.io/jQuery-contextMenu/docs.html). Am I missing something?
