### ISSUE TITLE
Issue with sub items callback

### ISSUE THREAD

**Issue by ben06600** [swisnl/jQuery-contextMenu#413]
Hello,

First, thanks a lot for the great job done ! 
JQuery context menu is really great, but I am right now blocked by an issue that I feel like a bug.

Please look at the attached example, it seems the callback attached to the option item is "replaced" by the one in the second loop

![image](https://cloud.githubusercontent.com/assets/20065294/16228399/0c1140da-37b7-11e6-8425-8f63a6f4e010.png)

Here is my code:
```
	$(function(){
		
		$.contextMenu({
			selector: '.context-menu-one', 		
			build: function($trigger, e) {	
				var options = { 
				
				  // start with an empty map
				  items: {
					"first": { 
					  "name": "first menu",
					  "items": {}
					},   					
					"second": { 
					  "name": "second menu",
					  "items": {}
					}              
				  }
				};
				

				var xml = "<TEST><CHILD LABEL=\"child 1\"  NAME=\"CHILD1\"/><CHILD LABEL=\"child 2\" NAME=\"CHILD2\"/></TEST>";
				xmlDoc = $.parseXML(xml);
				$xml = $(xmlDoc);
				
				$CHILD = $xml.find( "CHILD" );
				var currentSoort2 = "", content = $("#content");
				$.each($CHILD,function(i,item) {
					options.items["first"].items[i] = {
					 "name": $(this).attr('LABEL') ,"object": $(this).attr('NAME'), callback: function(itemKey, opt){ 
							alert("Add a " + opt.items.first.items[itemKey].object + " to node " + opt.$trigger.attr("id"));
							}
					};			
				});		

				var xml = "<TEST><CHILD LABEL=\"child 3\"  NAME=\"CHILD3\"/><CHILD LABEL=\"child 4\" NAME=\"CHILD4\"/></TEST>";
				xmlDoc = $.parseXML(xml);
				$xml = $(xmlDoc);				
				
				$CHILD = $xml.find( "CHILD" );
				var currentSoort = "", content = $("#content");
				$.each($CHILD,function(i,item) {
					options.items["second"].items[i] = {
					 "name": $(this).attr('LABEL') ,"object": $(this).attr('NAME') ,callback: function(itemKey, opt){ 
						alert("Add a " + opt.items.second.items[itemKey].object + " to node " + opt.$trigger.attr("id"));
						}
					};			
				});
				return options;
			}
		});
	`});`
```

[test.zip](https://github.com/swisnl/jQuery-contextMenu/files/325467/test.zip)

Thank you very much for having a look at this.
Ben.

**Comment by bbrala** [comment]
When i change the ``.items[i]`` to ``.items['firstmenu' + i]`` and ``.items['secondmenu' + i]`` it does work.

It seems the contextmenu puts the commands (callbacks) in one flat array, which could be fine, but if you use the same key twice  in another submenu appearantly it breaks... :( 

Think i need to add some sort of scoping of the callback keys so they wont override each other.

**Comment by ben06600** [comment]
Hello,

Indeed, using  a different key is working : .items['firstmenu' + i]

Many thanks for your help !!!

Ben.

**Comment by bbrala** [comment]
In the new release you can use the same name if you like. It will work then. So no real need to change code, just update the library.
