### ISSUE TITLE
Error using contextmenus in outer and inner div

### ISSUE THREAD

**Issue by wolfhermann** [swisnl/jQuery-contextMenu#419]
Hi there and gratulations for your great contextmenu control!

Using "nested contextmenus" the following actions does result in an wrong behaviour:
- Create OuterDiv and InnerDiv
- Create contextmenu for both divs
- Right click on outer div
- While contextmenu is open, rightclick on innerdiv
-> Error: Contextmenu of outer Div will be shown

see: [https://jsfiddle.net/h48cw88j/3/]

**Comment by wolfhermann** [comment]
First: I really forgot to say hello in my first message, sorry for that and here we go: Hi there and congratulations for the great contextmenu control!

Second: Sorry, the jsfiddle link was broken: [https://jsfiddle.net/wolfhermann/go2t8de0/](url)

**Comment by bbrala** [comment]
If you set the [``reposition``](https://swisnl.github.io/jQuery-contextMenu/docs.html#reposition) option to false you can fix this for you project i think.

**Comment by wolfhermann** [comment]
That did the trick! Thank you very much, keep up the great work!
