### ISSUE TITLE
Can this be a new feature? Remove dom from page.

### ISSUE THREAD

**Issue by wilecoyte78** [swisnl/jQuery-contextMenu#422]
Be able to remove the menu from the dom when a user clicks on a menu item or when the menu closes.

I am having issues because I have multiple menus with different class but its getting the very first menus title that was clicked.

**Comment by wilecoyte78** [comment]
I have this  and it's driving me batty that is is grabbing the first clicked menu's title:

		$('.context_menu_users').on
		(
			'click', 
			function(e) 
			{
		        var controller = this.getAttribute("data-controller");
		        var delete_visible = false;
		        var activate_visible = false;

		        switch (controller)
		        {
		        	case "users":
		        		delete_visible = false;
		        		activate_visible = true;
		        		break;
		        	default:
		        		delete_visible = this.getAttribute("data-delete");
		        		activate_visible = false;
		        }

			    $.contextMenu
			    (
				    {
				        selector: '.context_menu_users', 
				        trigger: 'left',
				        className: controller+'-title',
				        callback: function(key, options) 
				        {
				        	clicked = this[0];
					        id = clicked.getAttribute("data-id");
					        name = clicked.getAttribute("data-name");
					        controller = clicked.getAttribute("data-controller");
					        action = clicked.getAttribute("data-action");
					        can_delete = clicked.getAttribute("data-delete");
					        context_ment_items = null;
		            		switch (key)
		            		{
		            			case "add_user":
		            			case "add_department":
		            			case "add_group":
		            				key = "add";
		            				id = "";
		            			case "view":
		            			case "edit":
		            			case "delete":
		            			case "activate":
		            				usersAction(controller, key, id, name)
		           			}
				        },
				        items:
				        {
				            "view": {name: "View", icon: "view"},
				            "edit": {name: "Edit", icon: "edit"},
				            "delete": {name: "Delete", icon: "delete", visible: delete_visible},
				            "activate": {name: "Change Activation", icon: "activate", visible: activate_visible},
				            "sep1": "---------",
				            "add_user": {name: "Add New User", icon: "add-user"},
				            "add_department": {name: "Add New Department", icon: "add-department"},
				            "add_group": {name: "Add New Group", icon: "add-group"},
				        }
				    }
			    );

			   	// set a title for menu
			    $('.' + controller + '-title').attr
			    (
			    	'data-menutitle',
			    	controller.toLowerCase().replace
			    	(
			    		/\b[a-z]/g,
			    		function(letter)
			    		{
						    return letter.toUpperCase();
						}
					)
			    	+ " Menu"
			    );

		    }
	    );

**Comment by wilecoyte78** [comment]
Here is my jfiddle example 

https://jsfiddle.net/0qLzk7sb/

**Comment by wilecoyte78** [comment]
I figured it out if you go to the jsfiddle above it has the solution

**Comment by bbrala** [comment]
Hehe cool, glad i could help ;)
