### ISSUE TITLE
jquery 3.x breaks jqueryui (doesn't support getClientRects)

### ISSUE THREAD

**Issue by avim101** [swisnl/jQuery-contextMenu#423]
description: 
jQuery-contextMenu: v2.2.0
jquery.ui.position: v1.11.4

jquery issue: https://github.com/jquery/jquery/issues/3157

error:
`jquery.js:9779 Uncaught TypeError: elem.getClientRects is not a function`

solution:
update bower json
```
{
  "dependencies": {
    "jquery": ">=1.8.x <3.0.0"
  }
}
```

**Comment by bbrala** [comment]
Yeah i noticed this, see #407, when looked to update the bundled ui.position i couldnt download the new release that fixes it.
