### ISSUE TITLE
Add click event to text menu item

### ISSUE THREAD

**Issue by am2222** [swisnl/jQuery-contextMenu#432]
Hi,
I have created a dynamic menu item with a text box, How can I fire event when user clicks it?Is it even possible?
`"fold1": {
                              "name": "select",
                              "items": {
                                  "circl": { 
                                      "name": "Raduce", 
                                      type: 'text', 
                                      value: "100", 
                                      events: {
                                          
                                          keyup: function(e) {
                                              // add some fancy key handling here?
                                              window.console && console.log('key: '+ e.keyCode); 
                                          }}},
                                  "fold1-key1": { "name": "circle" },
                                  "fold1-key1": { "name": "circle2" },
                                  "fold1-key3": { "name": "poly" }
                              }
                          }`

**Comment by bbrala** [comment]
I think you can substitude the ``keyup:`` part with ``click:`` as stated in [events documentation](https://swisnl.github.io/jQuery-contextMenu/docs/items.html#events)
