### ISSUE TITLE
Font family when using font awesome

### ISSUE THREAD

**Issue by saschaende** [swisnl/jQuery-contextMenu#433]
You should add something like this...

`.context-menu-icon.context-menu-icon--fa span {
	font-family: Arial;
}`

Otherwise the font in the menu is wrong (looks like time new roman, in fact it is "FontAwesome")

**Comment by bbrala** [comment]
Thanks for reporting, i noticed something strange also yeah.

**Comment by gaurav6192** [comment]
@bbrala any updates?

**Comment by bbrala** [comment]
Sorry no, I haven't made the time yet to get back up to speed with the issues. I will make sure to reserve some time in the coming week.

**Comment by bbrala** [comment]
I added a [demo to the documentation](https://swisnl.github.io/jQuery-contextMenu/demo/fontawesome-icons.html), i don't see the issue there.

**Comment by gaurav6192** [comment]
@bbrala so just checked out the code there on the demo page, looks like there is this custom styling which is making it work -

`.fa, .rst-content .admonition-title, .rst-content h1 .headerlink, .rst-content h2 .headerlink, .rst-content h3 .headerlink, .rst-content h4 .headerlink, .rst-content h5 .headerlink, .rst-content h6 .headerlink, .rst-content dl dt .headerlink, .icon, .wy-dropdown .caret, .wy-inline-validate.wy-inline-validate-success .wy-input-context, .wy-inline-validate.wy-inline-validate-danger .wy-input-context, .wy-inline-validate.wy-inline-validate-warning .wy-input-context, .wy-inline-validate.wy-inline-validate-info .wy-input-context {
    font-family: inherit;
}`

Adding .fa{font-family: inherit;} to the css is making it work fine.

**Comment by gaurav6192** [comment]
Though the styling will still not be same as the one when using default context-menu icons. Try using one of each.

**Comment by bbrala** [comment]
Thanks for looking, didnt look deep enough appearantly. Sorry about that.
