### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by saschaende** [swisnl/jQuery-contextMenu#434]
Adding this:

`.context-menu-root {
	z-index:100000000 !important;	
}`

Fixed the problem, that the context menu was behind an active bootstrapp list group item.

But perhaps on opening the menu you could implement something like this function:

`function fwGetNextHighestZindex(){
	var zmax = 0;
	$('*').each(function() {
		var cur = parseInt($(this).css('z-index'));
		zmax = cur > zmax ? cur : zmax;
	});
	return zmax+1;
}`

**Comment by bbrala** [comment]
There is probably something set to an z-index relatively high then. You should check what is doing is, normally it should really be a problem.
