### ISSUE TITLE
How to open context menu for same class elements with different option/callback ?

### ISSUE THREAD

**Issue by eromoe** [swisnl/jQuery-contextMenu#435]
I am build a file manager base on react-redux. There is a file list, all file item has same class but different callback(action base on the fileitem's attributes ). What is the proper way to open context menu in each file item?

currently, I have to use something below in every FileItem Conponent, I think this cost much...
```
componentDidMount() {
    $.contextMenu({
        selector: '.'+ this.indexClassName(),
        callback: function(key, options) {
            var m = info.name + ':' + key;
            window.console && console.log(m) || alert(m);
        },
   ......
```

**Comment by Ruud-cb** [comment]
You can use the `build` property for the context menu. Based on the `$trigger` you can choose what you want to set as callback and what menu items you would like to show.
see: https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
I recommend you to determine the items based on the clicked file (which can be received via the `$trigger`) and use a single callback. Then based on the `key` you perform a certain action,

If you can add an extra property to each element that represents the file, you can get a value like this:
`var fileID = = $trigger.find('span').attr('property');`

**Comment by bbrala** [comment]
Thanks @Ruud-cb, that is indeed what i'd advise. :)
