### ISSUE TITLE
Submenu does not hide when hover over another disabled submenue-root

### ISSUE THREAD

**Issue by reinerBa** [swisnl/jQuery-contextMenu#436]
Hi,
i have a context menu wich contains two submenus in straight succession, in special cases one of them is disabled.
After hovering over the first submenu-root the submenue opens correctly but doesn't closes when hovering over the secound submenu-root because it its disabled.

![submenuhover](https://cloud.githubusercontent.com/assets/4329883/17433609/f4f0c48a-5b05-11e6-9af6-95589a26c924.png)

As i saw in the code the mouseenter Event seems to be the same for disabled and visible items, include the code with the comment "make sure only one item is selected".

**Comment by bbrala** [comment]
I'm not sure i feel like this is a bug, the element is like nothing, a spacer so i feel it shouldn't do anything really.
