### ISSUE TITLE
Submenus not working

### ISSUE THREAD

**Issue by davidwrmckay** [swisnl/jQuery-contextMenu#437]
Hi all,

I’ve been working on a project for the last few months which makes use of the SWIS jQuery Context Menu, and I wish to introduce submenus to the menus I have added, but am experiencing an issue.  The script used for the menus is generated in code, as my application (an ASP.NET C# project) requires many menus added to many items which are dynamically generated, so the scripts are generated then added to the page using a script manager, however, when I’ve attempted to add a submenu container item, it is simply appearing as if it were any other item, with no sub items.  As mentioned, this is from a script generated in code in a StringBuilder, and I’ve tried a number of variations on this, such as:

```
       [...]
       .Append(@"},""FormatStringCreate"":{name:""Set Format String..."",icon:""FormatStringCreate"",disabled:")
       .Append((!c1.EnableMenuOption_FormatStringCreate).ToString().ToLower())
       .Append(@"},""TimestampCreate"":{name:""Add Timestamp"",icon:""TimestampCreate"",disabled:")
       .Append((!c1.EnableMenuOption_TimestampCreate).ToString().ToLower())
       .Append(@"},""sep3"": ""---------"", ""myItemWithSubmenu"": { name: ""Textarea"", items: { ""edit"": {name: ""Edit"", icon: ""edit""} } },""ConditionalCreate"":{name:""Add Condition"",icon:""ConditionalCreate"",disabled:")
       .Append((!c1.EnableMenuOption_CreateItem).ToString().ToLower());
       [...]
```

The above forms part of a section of code which generates scripts such as the following, which shows another one of the attempts I made with the submenu.

```
$.contextMenu(
{
       selector:'#ctl00_cph_xt_tc_tp1_r1D1_Document_5_DocumentHeader_3_DocumentType_2,
                #ctl00_cph_xt_tc_tp1_r1D1_Document_5_DocumentHeader_3_DocumentType_21',

       callback:function(key, opt){__doPostBack('ctl00$cph$xt$tc$tp1$r1D1$Document_5$DocumentHeader_3$DocumentType_2',
'$$'+key+':'+'ctl00$cph$xt$tc$tp1$r1D1$Document_5$DocumentHeader_3$DocumentType_2');},

       items:{
       "CreateLink":{name:"Create Link",icon:"CreateLink",disabled:true},
       "sep1": "---------",
       "FieldRename":{name:"Rename Item",icon:"FieldRename",disabled:true},
       "FieldRemove":{name:"Remove Item",icon:"FieldRemove",disabled:true},
       "sep2": "---------",
       "FieldAdd":{name:"Add Field",icon:"FieldAdd",disabled:true},
       "AttributeCreate":{name:"Edit Attribute(s)",icon:"AttributeCreate",disabled:true},
       "ConstantCreate":{name:"Add Constant...",icon:"ConstantCreate",disabled:false},
       "FormatStringCreate":{name:"Set Format String...",icon:"FormatStringCreate",disabled:true},
       "TimestampCreate":{name:"Add Timestamp",icon:"TimestampCreate",disabled:false},
       "sep3": "---------",
       "myItemWithSubmenu": { name: "Textarea",
                                  { items
                                         { mySubmenu
                                                { name: "Command 1", callback: function(key, opt)
                                                       { alert("Clicked on " + key);
                                                       }
                                                }
                                         }
                                  }
                           },
       "ConditionalCreate":{name:"Add Condition",icon:"ConditionalCreate",disabled:false},
       "ContextCreate":{name:"Add Context",icon:"ContextCreate",disabled:false},
       "CounterCreate":{name:"Add Counter...",icon:"CounterCreate",disabled:false},
       "FunctionCreate":{name:"Add Function...",icon:"FunctionCreate",disabled:false},
       "PluginCreate":{name:"Add Plugin...",icon:"PluginCreate",disabled:false},
       "RegionCreate":{name:"Add Region",icon:"RegionCreate",disabled:false},
       "sep4": "---------",
       "ZoomIn":{name:"Zoom In",icon:"ZoomIn"}
}
});
```

However, when none of my attempts seemed to be working, I tried directly copying the contents of the example script shown in https://swisnl.github.io/jQuery-contextMenu/demo/sub-menus.html, and have seen the same issue there, so am struggling for ideas.  Can anyone provide any hints as to what might be happening here?

Kind regards,

David McKay.

**Comment by bbrala** [comment]
Are there any errors you see on the page? Especially if you have issues with the default demo, then it should be something weird in your page.

When you included the example code, did you also include the HTML with the correct class?

The first few things I would check:

* Is there no errors or warnings in your console in your browser? 
* In the network tab of the browser is the javascript for the context menu loaded?
* Same tab, is the CSS loaded?
* Is right click on the page working or prehaps closed of by another script? You can use the [trigger options to set it to open on left click](https://swisnl.github.io/jQuery-contextMenu/docs.html#trigger).
* Do you load the menu on domready/loaded? So inside `$(function(){ ... });`

**Comment by davidwrmckay** [comment]
Hi bbrala,

Thank you for your response.  There are no scripting errors, the appropriate CSS and JS files are loaded, and I am confident that the issue is not that the right click is being prevented, as the context menu is working, it's just that the item which contains a submenu is not, it just appears as if it were any other menu item.  Do you have any further suggestions on this?

**Comment by bbrala** [comment]
In the code you provided there is an issue in the definition of the submenu, perhaps that is a problem.

```
"myItemWithSubmenu": { name: "Textarea",
                                  { items
                                         { mySubmenu
                                                { name: "Command 1", callback: function(key, opt)
                                                       { alert("Clicked on " + key);
                                                       }
                                                }
                                         }
                                  }
                           },
```

Should be 

```
"myItemWithSubmenu":  { 
    name: "Textarea",
    items: { 
        mySubmenu: { 
            name: "Command 1", 
            callback: function(key, opt) { 
                alert("Clicked on " + key);
            }
        }
    }
},
```

Maybe that is the problem?

**Comment by davidwrmckay** [comment]
Hi bbrala,

Thanks again for your reply, but I've just run a test with this, and it also doesn't seem to be working.  I have tried a few different combinations, you may notice that there are two different versions in the two sections of sample code I provided in my initial post.  Perhaps it may be worth asking, what is the simplest form that a submenu can take?  Is the following valid?

"myItemWithSubmenu": { name: "Textarea", items: { "edit": {name: "Edit", icon: "edit"} } },
