### ISSUE TITLE
Order of menu items

### ISSUE THREAD

**Issue by amnond** [swisnl/jQuery-contextMenu#438]
Sorry - noticed this has already been addressed before.

A note regarding implementation: I've noticed the order of the menu items displayed assumes the order they are defined in the items map, however, it does not follow from the specification for Javascript dictionaries that any order can be counted on when iterating through the keys. While it appears that most browsers return an iteration order that is identical to the definition order, this is not guaranteed.

**Comment by Jamesx64** [comment]
Sorry if this has asked before but is it possible to call the context menu inside another function. How can this be done?

**Comment by bbrala** [comment]
@amnond gald it worked out :)

@Jamesx64 please check out: https://swisnl.github.io/jQuery-contextMenu/docs/plugin-commands.html#manually-show-a-contextmenu
