### ISSUE TITLE
Reopening contextMenu positions it incorrectly (not sure why)

### ISSUE THREAD

**Issue by Datamancer1110** [swisnl/jQuery-contextMenu#439]
I've been trying to figure out how to programmatically hide the contextMenu, then re-invoke it (because I want it to run build again).

So far, the most success I've had has been by doing
`$(...).contextMenu("hide").contextMenu();`

However, when I do that, the context menu gets placed in the wrong spot. I've got a fiddle you can check out here. Please advise, how can I convince the call to `.contextMenu()` to position like it usually does?

http://jsfiddle.net/uh4hroky/

Thanks

**Comment by bbrala** [comment]
Thanks for reporting, hopefully i have some time in the coming days to have a good look. Some users have reported issues with the hide function.

**Comment by Datamancer1110** [comment]
I'm so sorry, I pasted the wrong fiddle. I hope you didn't waste any time with that one. I'll update my original question, but here's the link, for posterity:

http://jsfiddle.net/uh4hroky/

**Comment by bbrala** [comment]
Hmm, when i update the fiddle to use recent version of the contextmenu i don't really see an issue?

http://jsfiddle.net/9pje4j68/
