### ISSUE TITLE
Installation via composer

### ISSUE THREAD

**Issue by kasoft** [swisnl/jQuery-contextMenu#440]
Hi,
i tried to install the Plugin via composer as a bower asset

"bower-asset/jQuery-contextMenu":"2.2.3",

Problem 1
    - The requested package bower-asset/jquery-contextmenu exists as bower-asset/jquery-contextmenu[0.5.2] but these are rejected by your constraint.

I finally installed via npm

"npm-asset/jQuery-contextMenu":"2.2.3",

This worked. Just to let you knwo. 

Thanks for the Plugin and the work!

**Comment by bbrala** [comment]
Thanks for the heads up. Seems it is a known issue.

https://github.com/fxpio/composer-asset-plugin/issues/188
