### ISSUE TITLE
Menu item type "html" needs better documentation

### ISSUE THREAD

**Issue by KraftyKai** [swisnl/jQuery-contextMenu#441]
I just struggled for a good 30 minutes with the HTML item type on the context menu.   The reason for my struggle rooted down to the documentation not being clear.  This might be common knowledge with contextMenus, but it's probably worth noting [in the docs](https://swisnl.github.io/jQuery-contextMenu/docs/items.html#type) that ...

1 - when using this type the actual content should be provided as the 'html' versus 'name' parameter.  I had to dive into the source code to figure this out.

2 - It's best to pass the html in element context versus string.  I've had predictable results when doing that but when using a string I've gotten varied mileage (sorry, I didn't muck around with strings enough to be able to pass any reliable information as to why that mileage may vary, just that I don't get entirely predictable outcomes).

Relatively low priority - this is just a documentation related issue.  It might help someone move faster in the future though.  Thanks for a great project :)

**Comment by bbrala** [comment]
Thanks for the compliment! 

Will update the docs at some point, thanks for taking to time to report. :)
