### ISSUE TITLE
Dynamic menu items.

### ISSUE THREAD

**Issue by tshenchotshering** [swisnl/jQuery-contextMenu#442]
I want to populate the menu from database dynamically using $.post() but am getting 

- jquery.contextMenu.js: 250 No items specified to show in contextMenu

- jquery.contextMenu.js:253 Uncaught Error: No Items specified
errors.

**my script:**

$.contextMenu({
                selector: '.c-t_menu',
                trigger: 'right',
                animation: { duration: 250, show: 'fadeIn', hide: 'fadeOut' },
                build: function ($trigger, e) {                                      
                    return {
                        callback: function (key, options) {
                             ......................
                        },
                        items: getMenuItem()
                    };
                }
            });
 
function getMenuItem(){
        //1st try
        $.post("url", { id :"..." })
         .done(function (data) {
             var $menu = {};
             for (var i = 1; i < data.length; i++) {
                    $menu[data[i].Name.toString()] = { name: data[i].Name.toString(), icon: "edit" };
                    //want to control disabling and enable base on data[i].isEnabled also.
            }
            alert($menu); // get as required.
            return $menu;
        });
       //**************************************

        //2nd try
        var $menu = {};
        $.post("url", { id :"..." }, function (data) {
             for (var i = 1; i < data.length; i++) {
                    $menu[data[i].Name.toString()] = { name: data[i].Name.toString(), icon: "edit" };
                    //want to control disabling and enable base on data[i].isEnabled also.
            } 
       });
       ($menu); // get as required.
       return $menu;
      /*****************************************
}

both try failed.  not populating menu. if I set ajax setting async to false then it is populating but i don't want to set async setting to false.

any help will be highly appreciated.

**Comment by bbrala** [comment]
You are doing a asynchronous request, that wont work. The menu will run the $.post and expect the output to be the menu. You need to do a synchronous request.

There is an open PR that will add a way to do this with promises, but i haven't had time to dive into it yet.

https://github.com/swisnl/jQuery-contextMenu/pull/431
