### ISSUE TITLE
Dymanic menu 

### ISSUE THREAD

**Issue by waque** [swisnl/jQuery-contextMenu#443]
I there!

I'm trying to populate the "add_shift" dynamically and it's not working. I was wondering if anyone can give me an and :)
thanks!

` $.contextMenu({
        selector: '.vis-selected , #mytimeline', 
        callback: function (key, options) {
            processContextClick(key);
            // window.console && console.log(m) || alert(m);
        },
        items: {
            "edit": { name: "Edit", icon: "edit" },
            "cut": { name: "Cut", icon: "cut" },
            "copy_item": { name: "Copy schedule", icon: "copy" },
            "copy_group": { name: "Copy group", icon: "copy" },
            "paste": { name: "Paste", icon: "paste" },
            "add_shift": { 
                name: "Add Shift",
                items:  function () {
                    $.each(shiftsMINdata,function(i, item){
                            
                        add_shift.items[i] = { name: item[0] };
                    });
                }
                    
                },
            
            "trade_shift": { name: "Trade Shift", icon: "edit" },
            "delete": { name: "Delete", icon: "delete" },
            
            "sep1": "---------",
            "quit": {
                name: "Quit", icon: function () {
                    return 'context-menu-icon context-menu-icon-quit';
                }
            }
        }
    }); `

**Comment by bbrala** [comment]
The items callback needs to return the items object to the menu. You are missing the return.

``` 
$.contextMenu({
    selector: '.vis-selected , #mytimeline', 
    callback: function (key, options) {
    processContextClick(key);
        // window.console && console.log(m) || alert(m);
    },
    items: {
      "edit": { name: "Edit", icon: "edit" },
      "cut": { name: "Cut", icon: "cut" },
      "copy_item": { name: "Copy schedule", icon: "copy" },
      "copy_group": { name: "Copy group", icon: "copy" },
      "paste": { name: "Paste", icon: "paste" },
      "add_shift": { 
          name: "Add Shift",
          items: function () {
                $.each(shiftsMINdata,function(i, item){
                    add_shift.items[i] = { name: item[0] };
                });
                return add_shift.items;
            }

            },

        "trade_shift": { name: "Trade Shift", icon: "edit" },
        "delete": { name: "Delete", icon: "delete" },

        "sep1": "---------",
        "quit": {
            name: "Quit", icon: function () {
                return 'context-menu-icon context-menu-icon-quit';
            }
        }
    }
}); ``

See the revised "Add shift" item.

**Comment by waque** [comment]
I forgot to return the item. But the thing is, when i try do put a break point or try to print "hello",
i can't even print that. It's not going there.

```
$.contextMenu({
        selector: '.vis-selected , #mytimeline', 
        callback: function (key, options) {
            processContextClick(key);
            // window.console && console.log(m) || alert(m);
        },
        items: {
            "edit": { name: "Edit", icon: "edit" },
            "cut": { name: "Cut", icon: "cut" },
            "copy_item": { name: "Copy schedule", icon: "copy" },
            "copy_group": { name: "Copy group", icon: "copy" },
            "paste": { name: "Paste", icon: "paste" },
            "add_shift": { 
                name: "Add Shift",
                items: function () {
                $.each($.parseJSON(shiftsMINdata),function(i, item){
                    add_shift.items[i] = { name: item[0] };
                    console.log("hello");
                });
                return add_shift.items;
            }
            },
            "trade_shift": { name: "Trade Shift", icon: "edit" },
            "delete": { name: "Delete", icon: "delete" },
            "sep1": "---------",
            "quit": {
                name: "Quit", icon: function () {
                    return 'context-menu-icon context-menu-icon-quit';
                }
            }
        }
    });

```

**Comment by bbrala** [comment]
Hmm, I might remembered wrong. For a dynamic menu you need to use the build option. You can't give a function to an item. 

https://swisnl.github.io/jQuery-contextMenu/docs.html#build

There is currently a pull request open to enable promises for items, but it might take a little while before that will make it into a version.

**Comment by waque** [comment]
I'm not sure if I understood correcly what you are saying, could you please give me an example on how to use the build option to dynamically add items?

```
$.contextMenu({
    selector: 'span.context-menu',
    build: function($triggerElement, e){
        return {
            callback: function(){},
            items: {
                menuItem: {name: "My on demand menu item"}
            }
        };
    }
});
```

Kind Regards

**Comment by bbrala** [comment]
There is a demo available at https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
