### ISSUE TITLE
contextMenu showing up although not configured

### ISSUE THREAD

**Issue by zopyx** [swisnl/jQuery-contextMenu#444]
Using Fancytree 2.19.0

This example configures two tree (#tree1, #tree2) where the right tree (#tree2) should have a context menu attached:

https://github.com/xml-director/xmldirector.demo/blob/context-m/xmldirector/demo/demo/fancytree.pt#L173-L189

This video shows a weird behavior:

no context menu attached on the left tree
context menu attached to the right tree
magically content menu also attached to the left tree
http://public.zopyx.com/contextmenu.mp4

Bug or feature?

**Comment by bbrala** [comment]
Fancy doesn't support it anymore, and the version used is a few years old. 

https://github.com/mar10/fancytree/issues/627

**Comment by bbrala** [comment]
I found a demo which does integrate a new version of the context menu. 

http://wwwendt.de/tech/fancytree/3rd-party/extensions/contextmenu/contextmenu.html
