### ISSUE TITLE
How To Access Other Properties When User Clicks

### ISSUE THREAD

**Issue by TEKFused** [swisnl/jQuery-contextMenu#449]
Hi!

I have created a context menu which has three levels:
1. Group
2. Contract
3. Report Name

When the user clicks on the third level (Report Name), the menu should then initiate the callback function and utilize the other properties associated with that key (logo, url, etc). The problem is that I cannot figure out how to access those other properties when I click on the report. Here is a JSFiddle:

https://jsfiddle.net/JakeRHill/ju13pom9/1/

Hopefully that is clear enough. Let me know if you have any questions.

Thanks!
Jake

**Comment by TEKFused** [comment]
I have made some progress on this. I determined that I can use the $selected argument in the callback function. I'm still not certain on how to access the properties directly, but my workaround is to assign the data to a class, and then parse the class data using the $selected argument. Does anyone know a better way?

**Comment by bbrala** [comment]
The items object it not really made to do this. Also, please use object for the items, at least, that is how it is described in the documentation. Perhaps you can use the callback function to save the url/logo in so it can call you personal function with the correct arguments.

I could imagine thought that having a property named ``data`` on the items which results in data tags on the menu item would be helpfull, this way you can easily add extra data to a menu item and just use ``opt.$selected.data()`` to get it back. That would be a new feature though.

**Comment by bbrala** [comment]
Closing due to no response.
