### ISSUE TITLE
generated markup invalid for xhtml

### ISSUE THREAD

**Issue by andreasplesch** [swisnl/jQuery-contextMenu#450]
The radio type (and perhaps others) generate invalid markup for a xhtml document. This results in a fatal exception. `"<input />"` would be compatible with both html and xhtml encoding.

Here is input menu demo as html:
https://andreasplesch.github.io/cobweb_dom/jQuery-ContextMenu/input.html

and as xhtml:
https://andreasplesch.github.io/cobweb_dom/jQuery-ContextMenu/input.xhtml

There is this console message:

Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

**Comment by andreasplesch** [comment]
I patched jquery.contextMenu.js to use `<input />` and it does have the desired effect:

https://andreasplesch.github.io/cobweb_dom/jQuery-ContextMenu/input_fixed.xhtml

In the process, it turned out that the `<select>` tag did not have an end tag as it should. So I added the end tag as well.

The patched js works with the html encoding as well. I tested on Chrome 52.02, FF 47 and IE11.

I could prepare a PR but the changes are rather trivial.

**Comment by bbrala** [comment]
Thanks for putting in the effort to create a patch. I'm on vacation right now, but will have a look at your pr when it arrived.

**Comment by andreasplesch** [comment]
#451 submitted.

**Comment by bbrala** [comment]
Thanks, from what i read it is valid in HTML5 also, but not in HTML4. But will have a look soon.

**Comment by andreasplesch** [comment]
My understanding is that `<input />` is not valid in HTML4 but that the w3c validation service at

https://validator.w3.org/

still recognizes it as strictly valid.

There are not many jquery based web pages which use HTML4 left but there may be only a few more which use XHTML.

The only browsers which may complain are perhaps IE6 or IE7 ?

**Comment by andreasplesch** [comment]
I created a simplistic html4 page to test:

http://rawgit.com/andreasplesch/cobweb_dom/93be0ba5f9c4904cf71be2755d308deea110651a/jQuery-ContextMenu/Inputv4.html

IE6 on Netrenderer.com is happy with it.

**Comment by andreasplesch** [comment]
Any plans or questions about this PR ? If it is lower priority as an enhancement, we would start to maintain and use a fork downstream.

**Comment by bbrala** [comment]
I will look at it soon, and talk with some colleagues if they think this might be problematic, if not, it'll be merged :)

**Comment by andreasplesch** [comment]
ok, thanks. I can understand that this is perhaps seen as risky given that xhtml is not used much. But I could not find a scenario where `<input />` would not work as expected.

**Comment by andreasplesch** [comment]
PR merged
