### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Ivanca** [swisnl/jQuery-contextMenu#452]
First of all I'm grateful for the library and much thanks for it.

But (there is always a but) using it for anything slightly advanced is proving to be a headache, why aren't there normal events to listen for? Examples

This doesn't exist:

```
$('.context-menu-one').on('contextmenu:show', function(){ /*code*/ })
```

After much looking at the code I discover you can do

```
$('.context-menu-one').on('contextmenu', function(){ /*code*/ });
```

Somehow I was assuming this event was only for triggering (i.e. not for listening), there is no example of a similar usage in the documentation

**Comment by bbrala** [comment]
Ok, sure, the [event documentation](https://swisnl.github.io/jQuery-contextMenu/docs/events.html) could be expanded with this use-case. Care to make a PR for [the documentation file](https://github.com/swisnl/jQuery-contextMenu/blob/master/documentation/docs/events.md)?

**Comment by bbrala** [comment]
Closing due to no response.
