### ISSUE TITLE
Events are never trigger when opening a contextMenu right after the other

### ISSUE THREAD

**Issue by Ivanca** [swisnl/jQuery-contextMenu#454]
Any custom mouse callbacks are never called if you open a context menu when there is another is already open,  this issue occurs because the overlay layer ("#context-menu-layer") takes a while to dissapear and before that happens the second context menu is already open so native events (i.e. mouseover) never had any chance of occurring.

``` js
$('.context-menu-one').on('> div', 'mouseover', function(){
    console.log('never happens')
});
```

This behavior happens even with `reposition: false`. As you may know this is not how the native context menu (e.g. Chrome context menu) works, when you right click another element when there is a context menu already open all pertinent events are triggered _before_ opening the new context menu.

**Comment by bbrala** [comment]
Thanks for the report. Can you provide a demo? This might be hard to fix though, the menu really needs that hidden overlay to be sure to hide when clicking outside the menu.

**Comment by Ivanca** [comment]
no time for creating demo, but waiting one millisecond (tick) to show the overlay and context menu should be enough to fix it (**after** being hidden, and default already prevented)

**Comment by Ivanca** [comment]
...looks like this plugin closes the context menu on "mousedown" like it should but it also prevents the default click that its suppose to happen under the new mouse position... that's not

**Comment by Ivanca** [comment]
I'm not gonna create a demo, you can keep your bug if you like it that much. I will develop my own context menu, with blackjack and hookers.

**Comment by bbrala** [comment]
Relax, i'll get to it. I understand you might be frustrated if you run into a bug. But I'm a bit busy at the moment, my baby girl doesn't allow me much time in the evening currently.
