### ISSUE TITLE
Icon function runs twice

### ISSUE THREAD

**Issue by moeiscool** [swisnl/jQuery-contextMenu#455]
If i run

`$i.append('<i class="fa fa-star"></i> `');`

it makes two stars. If i use the default method found in the docs I lose the "name" tag.

What is the correct way of using custom icons? please help.

default use :
```
$.contextMenu({
    selector: '[otb]',
    items: {
        status: {
            name: "Status",
            icon:function($o,$i,itemKey,item){
                $i.html('<i class="fa fa-star"></i> '+$o.selector);return 'context-menu-icon-updated';
            },
            callback: function(key, opt){
                alert("Clicked on " + key);
            }
        }
    }
});
```

**Comment by Ruud-cb** [comment]
Somehow the `$o.selector` doesn't return the name of your defined name. So use `item.name` to get the name.

When u use font awesome icons, just insert `{ name: "Status", icon : "fa-star" }` (without the first `fa`).

**Comment by bbrala** [comment]
Thanks @Ruud-cb, you should use the plugin itself if you want to use FontAwesome, check out the [documentation](https://swisnl.github.io/jQuery-contextMenu/demo/fontawesome-icons).
