### ISSUE TITLE
Preventing event bubbling

### ISSUE THREAD

**Issue by rogerdahl** [swisnl/jQuery-contextMenu#463]
Not sure if this is a bug, feature or just a question.

I'm trying to have two context menus on the same page. The first is on a div in a table and the other one is on the background. The problem is that, when I tap the div, the menu for the div opens and is then replaced by the menu for the background a fraction of a second later. I'm assuming that it is because the event bubbles up to the background after having triggered the menu on the div.

Is there a way to stop the menu for the background from opening when I tap the div?

**Comment by bbrala** [comment]
My first guess is to use the `trigger` option to [disable the trigger](https://swisnl.github.io/jQuery-contextMenu/docs.html#trigger) and [open the contextmenu manually](https://swisnl.github.io/jQuery-contextMenu/docs/plugin-commands.html#manually-show-a-contextmenu) with an [jQuery event](https://api.jquery.com/contextmenu/) on the div. You can prevent bubbling there.
