### ISSUE TITLE
How to reinitialize context menu?

### ISSUE THREAD

**Issue by tolerious** [swisnl/jQuery-contextMenu#464]
I want to reinitialize context menu, how can I do that, just type this code?but doesn't work.

```
$.contextMenu({...})

$.contextMenu({...})//  again
```

**Comment by bbrala** [comment]
I think you might just need to destroy then reinitialize. See [the docs](https://swisnl.github.io/jQuery-contextMenu/docs/plugin-commands.html#unregister-all-contextmenus) on how to destroy your inialized contextmenu.

**Comment by tolerious** [comment]
THX.
