### ISSUE TITLE
Can add scroll bar to submenu items?

### ISSUE THREAD

**Issue by tolerious** [swisnl/jQuery-contextMenu#466]
I create a lot of submenu items,  and is there a config property to show a scroll bar when there are so many submenu items?

**Comment by tolerious** [comment]
I think we can pass a parameter to initialization function to set a `max-height`, and add an `overflow-y:auto` property.

**Comment by bbrala** [comment]
Wouldn't it be possible just to use css to do this? The classes are pretty sane in their layout

**Comment by tolerious** [comment]
sure, currently I modify your css file to meet this requirement.  😄

**Comment by bbrala** [comment]
Yeah or just include it in your own to override the default styles. :)

**Comment by bbrala** [comment]
Should there be more people asking fur this feature I'll consider it. But for now, css should do fine.

**Comment by tolerious** [comment]
OK, thanks for your reply.

**Comment by Sisco21** [comment]
Hello,

I have a similar issue with the menu. I'm using the last version.

Look the Gif, my menu is very huge. I want to limit the height.
![MENU](https://user-images.githubusercontent.com/6603746/65149506-81076700-da22-11e9-8d98-bc2d0eb809cf.gif)

I have set max-height and overflow, but the result is worst.

Best regards.
