### ISSUE TITLE
Touch device sub-menu hover bug

### ISSUE THREAD

**Issue by Ruud-cb** [swisnl/jQuery-contextMenu#471]
When using the context menu on a small device, opening the menu is fine. But when tapping a sub menu, it sometimes needs to position the submenu over the root menu (because there is no space to the left or right). However, it looks like the menu triggers an hover and then registers a click. The result is opening the submenu and instantly press a button in that sub-menu.

Could you fix this? Probably don't allow hover on touch devices.

**Comment by bbrala** [comment]
Valid point, will think about a solution.

**Comment by bbrala** [comment]
Hmm, if i use the submenu demo i can select the submenu on my android device, but it seems i need to do a longpress to do it, could you see if you can also do it that  way?

**Comment by bbrala** [comment]
Closed due to inactivity.

**Comment by renebrain** [comment]
For me a regular click on the parent menu clicks the first item of the submenu instead of just opening it. That is causing a confusing behaviour for the user. It is also for the submenu demo on Android on Google Chrome happening for me. Can this somehow be prevented?
