### ISSUE TITLE
[bug] The contextmenu shows even if all items are set to visible:false

### ISSUE THREAD

**Issue by CaselIT** [swisnl/jQuery-contextMenu#473]
When all the item are set to `visible: false` the context menu will still show.

There is a typo [here](https://github.com/swisnl/jQuery-contextMenu/blob/6de698b7f642a325e986e0c5ceb6bee4259fc3cc/src/jquery.contextMenu.js#L332):
The `else if` condition should be `typeof e.data.items[item].visible !== 'undefined'` intead of `item.visible !== 'undefined'` since item is a string (the key representing an item).

**Comment by bbrala** [comment]
Thanks for reporting. :)

**Comment by bbrala** [comment]
Thanks again, committed the fix.

**Comment by madprops** [comment]
This is happening with latest (2.8.0). When all items are not visible a thin rectangle appears in the top left corner of the screen which can't be closed.
