### ISSUE TITLE
Menu content is not rebuild when right-click is triggered after the first time

### ISSUE THREAD

**Issue by wewake4** [swisnl/jQuery-contextMenu#475]
right-click to show context menu then move to other position then right-click again, content is not rebuild. But if you left-click then right-click it rebuild the content. So, it you want some kind like right-click on specific element with specific content menu. It has to left-click then right-click.

**Comment by wewake4** [comment]
reposition:false,

**Comment by bbrala** [comment]
Glad it worked out :)
