### ISSUE TITLE
Lack of documentation for proper installations?

### ISSUE THREAD

**Issue by jredd** [swisnl/jQuery-contextMenu#476]
Am I just missing the page for how to properly install this plugin? I'm using typescript and I believe I have it where typescript will pull it in and I can call on it. But it still won't work properly, and since I can't even find basic documentation on even installing the plugin properly I have no idea where to start trouble shooting.

**Comment by nelson6e65** [comment]
I use to install it via **[Bower](https://bower.io/)**, same as `jQuery`, `Bootstrap` and else: 

```
bower install jQuery-contextMenu --save
```

> https://bower.io/docs/tools/


About your problem with TypeScript... I have no idea what you meant.

**Comment by bbrala** [comment]
Hmm, if you use typescript, you probably use npm, just install [through npm](https://www.npmjs.com/package/jquery-contextmenu).

**Comment by 0xorial** [comment]
Who is supporting typescript definitions? They seem to be [outdated](https://www.npmjs.com/package/@types/jquery.contextmenu) and perhaps I could update them a bit...
