### ISSUE TITLE
Context Menu in Table Row Exclude Links

### ISSUE THREAD

**Issue by carlhussey** [swisnl/jQuery-contextMenu#480]
I have this menu working within a table and time some one clicks on a row.

However, some columns have links in them and I want to disable this context menu from opening if they right click on a link.

I tried the following: selector: 'tbody tr:not(a)'  

How can I prevent this from triggering? I also added "context-menu-disabled" to my links in the table but it is still fired.

**Comment by bbrala** [comment]
Hmm, probably preventing event bubbling on the links. 

```
$('tbody tr a').click(function( event ) {
  event.stopPropagation();
  // Do something
});
```
