### ISSUE TITLE
Nothing is working anymore

### ISSUE THREAD

**Issue by Displee** [swisnl/jQuery-contextMenu#484]
Erm... soo, nothing is working anymore.

https://swisnl.github.io/jQuery-contextMenu/demo.html

I thought that it was me, but the online demo is not working either, no context menu is being shown.

Please fix it asap, thank you.

**Comment by Papilla-Hitlers** [comment]
+
I download and save [this](https://raw.githubusercontent.com/swisnl/jQuery-contextMenu/e94aefab380fb9f8d2c34201fdd10119024bb945/dist/jquery.contextMenu.js) version.

**Comment by bbrala** [comment]
Hmm. I'll look at out after dinner. Sorry.

**Comment by Displee** [comment]
Thanks @Papilla-Hitlers, you saved my life.

**Comment by bbrala** [comment]
I've rolled out the fix in 2.4.1, sorry for breaking it! And thanks for letting me know so quickly.
