### ISSUE TITLE
dynamic names ?

### ISSUE THREAD

**Issue by oceatoon** [swisnl/jQuery-contextMenu#489]
Hi 
first of all thanks for the great pluggin :)
I tried googling for this but didn't find any working code 
I'm using the contextmenu for adding favorites, once added I need to change the label to remove favorite 
items: {
	        add2fav: { 
	        	name: function($element, key, item){ 
        			var str = ( userConnected.favorites && userConnected.favorites[] ) ? "Retirer de vos favoris" : "Ajouter à vos favoris";
        			return str; 
        		},

I tried something like this 
I'm sure I missed something obvious or a link somewhere 
thanks for the help

**Comment by bbrala** [comment]
Try and use the ``build`` option to build the menu on open. You can then just read the favorites settings and build the menu from there.

**Comment by oceatoon** [comment]
thanks for the quick answer 
I had found this 
https://swisnl.github.io/jQuery-contextMenu/demo/async-create.html
but couldn't understand how it would work to switch 
do I have to make two function add and remove ?
I think it could be a simple and good use case for many people

**Comment by bbrala** [comment]
Sorry, i was on mobile so was hard to get a proper link. I ment [this demo](https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html), you can just use that option to build the menu based on the state of the favorite list.

**Comment by oceatoon** [comment]
I managed to build the menu fine, but still haven't sorted out how to add rules on click of the element ?
I need to switch between to states ADd /Remove according if the element is in my list or not 
any light in my darkness ? :) 
cheers
