### ISSUE TITLE
class selector is not working

### ISSUE THREAD

**Issue by farrukhpisces** [swisnl/jQuery-contextMenu#490]
if an element is added later in body then class selector is not working
I am working with SVG element and i need to open Menu on line click but selector should be class.
and I am generting SVG line dynamically. 

   ` selector: '.partner',
       callback: function (key, options) {
           $('.context-menu-list').hide();
           PartnerContextMenuActions(key, options);

    },`

**Comment by bbrala** [comment]
What version of jquery are you using?

**Comment by bbrala** [comment]
Closing due to no response.
