### ISSUE TITLE
icons are not loading

### ISSUE THREAD

**Issue by farrukhpisces** [swisnl/jQuery-contextMenu#492]
I am using this plugin which is awesome. But i am facing an issue regarding Icons. I have copies all the resource like jquery CSS and icons, But icons are not loading in my Context Menu.
Please guide me where should I place my icons?

**Comment by bbrala** [comment]
Currently I'm on mobile so I can't really find the link. There is a page in the docs about this.

**Comment by bbrala** [comment]
What icons are you using? Are you trying to add SVG icons? If so so the following (with npm installed ;))

1. Clone the repository
2. Add the icons to `./src/icons/` 
3. Run `npm install`
4. Run `gulp css`

**Comment by bbrala** [comment]
Closing due to no response.
