### ISSUE TITLE
Disable property doesn't work

### ISSUE THREAD

**Issue by whiteblackkeys** [swisnl/jQuery-contextMenu#493]
The disable property doesn't seem to work properly, even on the demo on your website: 
[Website](http://swisnl.github.io/jQuery-contextMenu/demo/disabled-changing.html)

The problem should be here: 

`  if (root.selectableSubMenu && (!opt.items[key] || $this.is('.' + root.classNames.disabled + ', .context-menu-submenu, .context-menu-separator, .' + root.classNames.notSelectable))) {
                    return;
                }`
root.selectableSubMenu returns false

**Comment by Coldwav3** [comment]
Perhaps is a wanted behaviour

**Comment by bbrala** [comment]
Thanks for reporting. I'll simplify that construction,. :)
