### ISSUE TITLE
Paste Functionality? 

### ISSUE THREAD

**Issue by Jukari2003** [swisnl/jQuery-contextMenu#494]
I've been able to get Cut/Copy working. But is there a way to get paste working? I know that browsers block paste from the context menus for security reasons (what I learned during my research) Is there a work around?

I had an idea to put a text input inside the menu where the paste item is and allow the user to right click and use the browser context menu to paste in that... but right click is blocked when inside the context menu, on both HTML styles and native context menu styles.

Any suggestions?

**Comment by bbrala** [comment]
Maybe you should look at the Clipboard api (http://caniuse.com/#search=paste)? There are quite a few caveats, but you should be able to handle copy/paste in some way.
