### ISSUE TITLE
Screen reader not working for content menu items

### ISSUE THREAD

**Issue by nishant09** [swisnl/jQuery-contextMenu#496]
I'm using jquery datatable pluging in our product. When I right click on a row I pop up jquey context menu where i have bunch of items.  I can tab easily tab through these items,on escape it closes the menu, home button will take me to the first menu. However, two things are not working here

1) Screen reader is not reading the items in the list. It just says "Tab" while tabbing through the items
2)arrow up and down are also not working. i have to either press tab or shift tab to navigate. (however,i noticed arrow up and down actually navigating through the datatable items.)

can you give me an insight into these two behavior ? I really wanna make screen reader working

**Comment by bbrala** [comment]
For the problem with the arrow keys, it seems the datatable is stopping those from getting to the context menu. You might need to check in that plugin if you can disable them when the event source it in the context menu.

Regarding the screenreader, i really dont know. What screen reader? And does it work on the demo in the documnetation?

**Comment by nishant09** [comment]
Thank you. 
I was able to make this work by putting focus on the context menu. Screen reader reads it properly
