### ISSUE TITLE
how to put focus on context menu manually

### ISSUE THREAD

**Issue by nishant09** [swisnl/jQuery-contextMenu#497]
I want to put focus on contextmenu after i right-click on the table row. what's jQuery selectors to select and manipulate HTML element for contextmenu to put the focus ? 

$.(".  ???").focus();

any help will be appreciated

thanks

**Comment by bbrala** [comment]
If you inspect the [demo](https://swisnl.github.io/jQuery-contextMenu/demo.html) you see the root elemnt is called '.context-menu-root'.
