### ISSUE TITLE
Reusable Selector IDs issue

### ISSUE THREAD

**Issue by gfmclean** [swisnl/jQuery-contextMenu#499]
I have two types of context menus, namely text and image context menus for divs which contain respectively an image or text.  The user has the ability to insert and delete such containers.  The issue is as follows:

1.  I create a div with an id of d1 (a text container).
2.  I assign it a text context menu
2.  I delete the div under 1.
3.  I create a div with an id of d1 (an image container).
4. The div (the image div under 3) I create now has a text context menu because the id's are being reused.

Question:  Is there a way to unassign the 'selector' of a  context menu when the said 'selector' has been deleted?

I appreciate any assistance I can get with this.  At the moment I am no longer reusing the IDs to overcome this issue.  However, I would like to keep the IDs sequential for clarity in my app.

Godfrey

**Comment by bbrala** [comment]
I would think you can fix this by using classes for the elements you want to trigger a contextmenu on. Why not a `class="text-menu"` and `class="image-menu"` and bind the context menu on those. That should work.

**Comment by gfmclean** [comment]
bbrala, Thank you for the response. I shall rewrite some of the items and see if I can swing that.  I am sure it shall work.
