### ISSUE TITLE
Can't override FA icon colours 

### ISSUE THREAD

**Issue by alopez25** [swisnl/jQuery-contextMenu#501]
I don't seem to be able to override the colour of font-awesome icons via CSS. I'm using a rails gem so I have no access to the css file but I don't seem to find the selector for overriding colour.
Could you point me to the right way of doing so?

**Comment by bbrala** [comment]
Try these (from the src). This are the classes for the font-awesome icons.

```
.context-menu-icon.context-menu-icon--fa {
  display: list-item;
  font-family: inherit;
}
.context-menu-icon.context-menu-icon--fa.context-menu-hover:before {
  color: #fff;
}
.context-menu-icon.context-menu-icon--fa.context-menu-disabled::before {
  color: #bbb;
}
```

**Comment by alopez25** [comment]
Thanks a lot mate!
