### ISSUE TITLE
ContextMenu appears with wrong position

### ISSUE THREAD

**Issue by wolf-w** [swisnl/jQuery-contextMenu#502]
This hapens, when the body has `max-width` or somethink like that.
You need to calculate the position, relative to the `offsetParent` of the `opt.$menu`

QuickFix:
Rewrite the `else` on line `172`:
``` js
position: function (opt, x, y) {
  var offset;
  // determine contextMenu position
  if (!x && !y) {
    opt.determinePosition.call(this, opt.$menu);
    return;
  } else if (x === 'maintain' && y === 'maintain') {
    // x and y must not be changed (after re-show on command click)
    offset = opt.$menu.position();
  } else {
    // x and y are given (by mouse event)
    offset = {top: y, left: x};
  }
```
to:
``` js
} else {
  // x and y are given (by mouse event)
  //but.. they are fixed x and y .. so we need to get the offsetParent's position to recalculate for our absolute position
  var offsetParentOffset = opt.$menu.offsetParent().offset();

  offset = {top: y - offsetParentOffset.top, left: x -offsetParentOffset.left};
}
```
as you can see, this fix is only used, when x and y are present from mouse `event`

**EDIT:**
changed from position() to offset()

**Comment by bbrala** [comment]
I've tried to reproduce this, but i can't. Can you provide a test page or the HTML that breaks is here on maybe on jsfiddle?

**Comment by apptaro** [comment]
I have the same issue. Here's the test page:
https://jsfiddle.net/apptaro/rf765goz/
