### ISSUE TITLE
Use function for "selected"

### ISSUE THREAD

**Issue by f69m** [swisnl/jQuery-contextMenu#503]
Hi, first thanks for this great plugin! Works great, I have just been running into one issue. 

For an item with type "select", I would like to compute the value for the "selected" attribute from the contents of the targeted HTML element. This is similar to what works great for attribute "disabled".

Example (simplified from my actual code):
```
items: {
    select: {
        name: "XYZ",
        type: "select",
        options: selectOptions,
        selected: function(key, opt) {
            return ... // would like to compute from opt.$trigger
        }
    }
}
```

What I see is that the function is called once on contextMenu creation and "opt" does not have a suitable value.

Is there another way to compute the value for "selected" dynamically, or is this actually a feature request?

**Comment by bbrala** [comment]
Well, the only way to build the menu dynamicly is using the on demand method. This will run a function to calculate all the options every time you open the menu.

See: https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
