### ISSUE TITLE
Font-Awesome causing items to render horizontally

### ISSUE THREAD

**Issue by shadowpuppetz** [swisnl/jQuery-contextMenu#504]
I'm building a context menu with the following code:

$.contextMenu({
                selector: '.pmservice-menu',
                trigger: 'left',
                callback: function (key, options) {
                    var m = "clicked: " + key;
                    alert(options.$trigger.data("serviceid"));
                },
                items: {
                    "Add Note": { name: "Add Note", icon: "fa-comment-o" },
                    "Skip": { name: "Skip", icon: "fa-ban" },
                    "Record Service": { name: "RecordService", icon: "fa-wrench" }
                }
            });

When using the font awesome icon names, the menu comes out all horizontal.  using the built in icons or no icons gives me the expected result
![horizonalmenu](https://cloud.githubusercontent.com/assets/25669185/22795349/001bf470-eebc-11e6-9a36-2dd80ba03a3c.png)

**Comment by bbrala** [comment]
Did you load the currect css? You need to include the ``jquery.contextMenu.css`` or ``jquery.contextMenu.min.css`` and the CSS for fontawesome.

**Comment by shadowpuppetz** [comment]
Yes, I have this in my head tag

<link href="https://swisnl.github.io/jQuery-contextMenu/dist/jquery.contextMenu.css" rel="stylesheet" type="text/css" />

**Comment by bbrala** [comment]
Ok, it really should be somthing in your CSS that is giving the elements display:inline or something. Quite hard to debug without a working example.

**Comment by bbrala** [comment]
Closed due to inactivity.
