### ISSUE TITLE
Accesskey jQuery Modal Dialog not working

### ISSUE THREAD

**Issue by CiTRO33** [swisnl/jQuery-contextMenu#506]
Hello, 

i upgraded to the latest Version of contextmenu. 
With the new Version the accesskeys didn't work anymore in modal jQuery Dialogs
I created a demo to show the problem:
https://jsfiddle.net/t31wtnny/
The contextmenu can be triggered with right click on"test".

i figured it out that  Linie 552  cause the problem:
`getZIndexOfTriggerTarget(e.target);`
 // If targetZIndex is heigher then opt.zIndex dont progress any futher.
// This is used to make sure that if you are using a dialog with a input / textarea / contenteditable div
 // and its above the contextmenu it wont steal keys events
`if (targetZIndex > opt.zIndex) {
                    return;
}`

**Comment by bbrala** [comment]
When i open the demo i do get an alert, am i missing something?

**Comment by CiTRO33** [comment]
Hey,
i updated the fiddle https://jsfiddle.net/t31wtnny/1/   i think because of mixed content loading (http/https) something didn't worked correct.
It should look like: 
![grafik](https://cloud.githubusercontent.com/assets/6649551/23368920/c61f1b5a-fd0f-11e6-9a0b-b7359e0f8c00.png)

the alert isnt comming if i use the accesskey "o" to open the "overview"-menu item.

**Comment by bbrala** [comment]
Ah i can reproduce the problem now. Thanks

**Comment by CiTRO33** [comment]
Hey @bbrala 
did you had some time to look into this problem?

**Comment by bbrala** [comment]
Hmm, i've looked at the problem, and i think the fact you use `modal:true` you block the interaction with everything else through the modal dialog. From the documnetation:

> If set to true, the dialog will have modal behavior; other items on the page will be disabled, i.e., cannot be interacted with. Modal dialogs create an overlay below the dialog but above other page elements.

I don't think i can really fix that.

**Comment by CiTRO33** [comment]
i think the problem come with the pull https://github.com/swisnl/jQuery-contextMenu/pull/335

I debugged into the fiddle  https://jsfiddle.net/t31wtnny/1/ 

![image](https://cloud.githubusercontent.com/assets/6649551/24321407/45cef96a-114c-11e7-9532-401f2be597dc.png)

So the zIndex of the Dialog is behind (101) the contextMenu (102). 
(This could be, because the contextMenu is build on the fly via the build function) 
But in the check ( Line 552) on the zIndex the opt.zIndex is used.

If i understand the zIndex option http://swisnl.github.io/jQuery-contextMenu/docs.html#zindex correctly  
this is only an offset that will be added on creation of the contextmenu.

Maybe this change on line 552 could fix the problem:
` if (opt.$menu &&  parseInt(targetZIndex,10) > parseInt(opt.$menu.css("zIndex"),10) ) {  return; } `

But i dont know if this break the the pull https://github.com/swisnl/jQuery-contextMenu/pull/335


I also tried this method: https://api.jqueryui.com/dialog/#method-_allowInteraction 
but also here the line 552 stops the accesskey to work.

Maybe you can use this information to find a solution. 
Thanks!

**Comment by bbrala** [comment]
Hmm, thanks for looking a little deeper for a possible explaination. It sounds quite reasonable... I'll have to test a bit to see if it is indeed an error in logic regarding the zIndex.

**Comment by CiTRO33** [comment]
Hey @bbrala,
did you had some time to test this?
