### ISSUE TITLE
Using jQuery-contextMenu in Angular-CLI

### ISSUE THREAD

**Issue by AndreAlves10** [swisnl/jQuery-contextMenu#508]
Hello,

I'm developing an Angular2 app, using Angular-Cli and I need to create a custom right-click context-menu. Yours seem to be exactly what I need.

Is it possible to integrate jQuery-contextMenu in an Angular2 project, which uses Typescript instead of JQuery?

Thank you!

**Comment by bbrala** [comment]
Currently is depends on jQuery, and there is no real way around that right now. 

There was someone who made a angular connector a few years back for the contextmenu, but i'm not sure that really helps you.

https://github.com/ariesjia/angular-contextMenu/

**Comment by AndreAlves10** [comment]
Thank you @bbrala, I'll take a look at that.
