### ISSUE TITLE
Nested context menu goes off-screen if parent is near the right.

### ISSUE THREAD

**Issue by Clement-E-Todd** [swisnl/jQuery-contextMenu#509]
While it appears that the parent context menu has logic to always keep it fully onscreen, the nested menus always render to the right of it. So, if the parent is near the right side of the screen, the nested menu will be cut off at the edge of the window.

In my example, I have a list on the right-hand side of my UI whose items can be right-clicked for a context menu. This context menu has nested items and it is impossible to read what they are. If there is not enough space for the nested menu on the right side of the parent, it should render on the left side instead.

![nested](https://cloud.githubusercontent.com/assets/2318146/23515944/ba55499e-ff39-11e6-986d-1ac6efb3080a.png)

**Comment by bbrala** [comment]
Hmm, good point. Thanks for the report.

**Comment by bbrala** [comment]
Could you include jquery.ui.position? This should fix the issue. Loading that extension will help make the positioning smarter.
