### ISSUE TITLE
Menus on parent and child crashes in FireFox

### ISSUE THREAD

**Issue by stSaHiB** [swisnl/jQuery-contextMenu#510]
If you got a menu on an element and you put another menu on a child of that element (with a different trigger) you get:
`TypeError: Argument 1 of Document.elementFromPoint is not a finite floating-point value.`
and you can't close the childs menu any more (at least the first one you open). I've tested it on chrome, Opera and Edge - works fine. Only Firefox (v52.0 x64) throwing that TypeError. 

I prepared a js fiddle: [http://jsfiddle.net/s43ba7wx/](http://jsfiddle.net/s43ba7wx/)

In my case I got a right click menu for the `<tr>`'s of a table, but also a left click version of the menu on a button in each `<tr>` for mobile users. So it's not an abstract "how-can-i-crash-it-scenario", but a real life case :-)

**Comment by bbrala** [comment]
Thanks for the report with fiddle!. I can imagine the code borking right there.  A lot of the scoping is done on which element it triggers and it figured out which button it was in the code. 

I'm not sure if this really is fixable in a reasonable amount of time, but I'll have a look.

**Comment by bbrala** [comment]
This seems to be fixed in master. See the updated fiddle:

http://jsfiddle.net/s43ba7wx/2/

**Comment by stSaHiB** [comment]
sorry for beeing late, I was busy with my project. (release is close, so I was checking this "open problem" on my list)

Well, 2.5.0 / your fiddle isnt working for me with FireFox 54 - same errorMessage and problem :-(

Chrome 60 is even worse - Menu is bubbeling between parent and child menu and then closing after ~0.5sec, while the old version (my fiddle) was "better": the parent menu was shown (which is wrong) after some bubbeling

Edge - same problem as Chrome.

I really appreciate your help!

**Comment by stSaHiB** [comment]
I've just updated my project to 2.7 - problem seems solved, at least in my project!
Thanks alot!!!
