### ISSUE TITLE
can not input text in input dom

### ISSUE THREAD

**Issue by lerit** [swisnl/jQuery-contextMenu#514]
call contextMenu from a dialog,but i can not input anything
https://jsfiddle.net/t31wtnny/2/

**Comment by bbrala** [comment]
This seems related to #506. Thanks for supplying a fiddle :)

**Comment by bbrala** [comment]
Note to self, unrelated it seems unfortunately.

**Comment by bbrala** [comment]
It seems to be related to the close button, if i remove the header from the diallog it seems fine. I tried to find the exact reason but couldn't get there unfortunately. 

Could you see if there is perhaps settings in dialog that can help you?

**Comment by lerit** [comment]
i find if i set dialog div(with class ui-dialog) tabindex='9999999999999999999999999' can resolve it ,but i do not know why!the number is not a fixed number,and some time success some time fail.
