### ISSUE TITLE
Required Files

### ISSUE THREAD

**Issue by SoftCircuits** [swisnl/jQuery-contextMenu#518]
I'm upgrading from an older version of contextMenu. I can see you've added a bunch of new stuff, including new javascript files, icons, fonts, etc. But I really just want the core functionality.

Does it indicate anyplace what the minimum required files are? It looks like there are now additional javascript files. Do I need all of them? Ideally, I'd be able to get by with just a single script file and a CSS file.

Thanks.

**Comment by bbrala** [comment]
To get the basic contextmenu functionality you need the files in the `dist` folder. You could skip `jquery.ui.position.js` if you want, that is optional. The font files are needed to get the standard icons available to you.

**Comment by SoftCircuits** [comment]
Thanks, and sorry to be a pest. But I just want the menu. I don't need any icons. Do I still need the font files?

**Comment by bbrala** [comment]
You could use no icons sure. Css might not be optimal then thought.
