### ISSUE TITLE
How to add callback function for Ajax Dynamic Items

### ISSUE THREAD

**Issue by cyril-varoom** [swisnl/jQuery-contextMenu#524]
I am trying to load a menu dynamically using an AJAX call to server. 

On the Context menu I have

assigneeStatus: {
                            name: "Update Status",
                            icon: 'fa-flag',
                            items: loadStatuses(),
                        }

and the function

 var loadStatuses = function() {
        return $.ajax({
            url: SYSURL + '/entities/statusitems',
        });
}

and on the server this returns

public function statusItems(Request $request) {
        $statuses=Status::where('schedule_type', 'client')->get();
        $StatusItem=[]; $StatusArray=[];

        foreach ($statuses as $status) {
            $StatusItem['name']=$status->status_text;
            $StatusItem['icon']=$status->status_icon;
            $StatusItem['callback']="function(key, opt){updateAssigneeStatus(this[0].id.substr(5), key);}";
            $StatusArray[$status->id]=$StatusItem;
        }

       return $StatusArray;
    }

So, the menu loads fine but I cannot figure out how to pass the callback correctly. Obviously in this case I need to pass it in quotes but this then isn't a valid javascript object. Have tried lots of things but cannot seem to find a solution!

I don't get any errors but the callback function doesn't fire.

**Comment by bbrala** [comment]
You need to make sure it ends up as exaclty a json array as you normally specify items. Also `$.ajax` is asynchronous, so it probably wont work like that. You'd need promises probably.

Some documentation
https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
https://swisnl.github.io/jQuery-contextMenu/demo/async-create.html
https://swisnl.github.io/jQuery-contextMenu/demo/async-promise.html

You could also add the resulting HTML so i can check what the result is if you like :)
