### ISSUE TITLE
Open New Context Menu while old is open -> wrong menu items shown ( from old instance )

### ISSUE THREAD

**Issue by jkamuf2s** [swisnl/jQuery-contextMenu#526]
If you have two context menu instances bound to two nested div elements.

See This JSFiddle: https://jsfiddle.net/w3ovfj15/15/

How to produce the BUG:
Right Click on the green `outer` div and directly ( without closing the opened context menu by a left click ) right click into the blue `inner` div.

The context menu entries from `selector: '#outer'` will be shown in the `selector: '#inner'` context menu.

This only happens because `inner` is positioned that it  covers some surface of `outer`. Vice versa the BUG does not occur.

For my application it is a big BUG because the user has to close the context menu before he can open it on another div.

**Comment by bbrala** [comment]
In order to have a check for a new menu, please use the `reposition: false`, this will reevaluate the menu and show the correct one.

See updated fiddle:
https://jsfiddle.net/w3ovfj15/19/
