### ISSUE TITLE
Specific action when CTRL + left mouse clicked

### ISSUE THREAD

**Issue by lightframes** [swisnl/jQuery-contextMenu#529]
Hello,
I can't figure out how to get this. I'd like to open a new tab when I click left mouse + CTRL on Edit menu but I can't find a way to verify if CTRL is clicked.
If I can find it i can put in callback window.open when Edit is clicked using CTRL and window.location when it's clicked NOT using it.

**Comment by bbrala** [comment]
Hmm, this is a bit hard at the moment. There is a recent PR open that adds the original event to the custom callback so that might be a solution. I'll try and merge the pr soon.

**Comment by lightframes** [comment]
Hi Bjorn, I think this is what I need, so I can check in the custom callback the original event and activate different actions. Let me know when you have completed the merge so I can get the new code and try it.

**Comment by bbrala** [comment]
yeah wI'll do that, thanow.

**Comment by bbrala** [comment]
Merged and released in version 2.5.0

**Comment by lightframes** [comment]
Hi Bjorn,
this is my code but it seem it doesn't work what i need, neither with the
new version. I think I did something wrong. Coul you please help me?

$(function(){
    $('#table-results').contextMenu({
        selector: '.result-row',
         trigger: 'left',
        callback: function(key, options) {
            var m = "clicked: " + key + " on " + $(this).text();
            window.console && console.log(m) || alert(m);
        },
        items: {
            "edit": {name: "Modifica", icon: "edit",
            callback: function(key, options) {

                    $(document).on('keydown',function(event){
                        alert(event.which);
                        if(event.which=="17")
                            cntrlIsPressed = true;
                    });

                    if(cntrlIsPressed==true)

window.open("tuweb/offers_mod.php?id="+$(this).attr('row-id')+"&mod=si");
                    else

window.location="tuweb/offers_mod.php?id="+$(this).attr('row-id')+"&mod=si";
                }}
        }
    });
});

Best Regards
Stefano

2017-05-25 14:18 GMT+02:00 Björn Brala <notifications@github.com>:
