### ISSUE TITLE
Looking for fonts inside "css/font" [instead of "../fonts"

### ISSUE THREAD

**Issue by acabra85** [swisnl/jQuery-contextMenu#530]
Great product!, only a minor detail, 
I have install the plugin through npm, but when i provide my dist folder for my app (using gulp) to build the assets folder as follows.

assets
   js
      jquery.contextMenu.min.js
   css
      jquery.contextMenu.min.css
   fonts
      all the fonts from context menu

I've realized that the default icons fail to load,  because the current file ' jquery.contextMenu.min.css' is looking for the fonts inside a folder "css/font" whereas the standard should be to look for them in "../fonts".

Looking forward for this improvement.

Kind Regards!

**Comment by bbrala** [comment]
Thanks! 

The problem is this change would create problems for other people who expect it there.
