### ISSUE TITLE
Font style is ignored when using FontAwesome 

### ISSUE THREAD

**Issue by Thallius** [swisnl/jQuery-contextMenu#534]
When you choose a FontAwesome icon on the menu it is not possible to use a custom font on the text behind the icon (or I am not able to do this :)

Regards

Claus

**Comment by bbrala** [comment]
You should be able to use `.context-menu-list { font-familiy: arial; } ` or any other font without a problem to set the font.

**Comment by Thallius** [comment]
I tried it. Font-height is used but font-family and font-weight is ignored. When I remove the Icon from menu the right font with selected weight is used.

**Comment by bbrala** [comment]
Then you might need to be more specific unfortunately. Perhaps `.context-menu-list .context-menu-icon.context-menu-icon--fa { font-familiy: arial; }` or `span.context-menu-icon.context-menu-icon--fa { font-familiy: arial; }`
