### ISSUE TITLE
Font awesome icons not showing

### ISSUE THREAD

**Issue by dviljoen** [swisnl/jQuery-contextMenu#535]
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" />
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.5.0/jquery.contextMenu.min.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.5.0/jquery.contextMenu.min.js"></script>

...

            $.contextMenu(
            {
                selector: '.context-menu',
                items: {
                    "assign": {
                        name: "Assign",
                        icon: "hand-pointer-o",
                        callback: function (key, options) { $("#AssignDialog").modal('show'); }
                    },
                    "updates": {
                        name: "Update",
                        icon: "edit",
                        callback: function (key, options) { $("#UpdatesDialog").modal('show'); }
                    },
                    "scripts": {
                        name: "Script",
                        icon: "file-text",
                        callback: function (key, options) { $("#ScriptsDialog").modal('show'); }
                    },
                    "pause": {
                        name: "Pause Data",
                        icon: "pause",
                        callback: function (key, options) { $("#PauseDialog").modal('show'); }
                    },
                    "mesh": {
                        name: "Mesh Network",
                        icon: "cloud",
                        callback: function (key, options) { $("#MeshDialog").modal('show'); }
                    },
                    "location": {
                        name: "Location (Zone)",
                        icon: "location-arrow",
                        callback: function (key, options) { $("#LocDialog").modal('show'); }
                    },
                    "deletedata": {
                        name: "Delete",
                        icon: "trash",
                        callback: function (key, options) { $("#DelDialog").modal('show'); }
                    }
                },
                events: {
                    show: function (opt) {
                        var $this = this;
                        $.contextMenu.setInputValues(opt, $this.data());
                    },
                    hide: function(opt) {
                        var $this = this;
                        $.contextMenu.setInputValues(opt, $this.data());
                    }
                }
            });

The only one that shows up is "edit" icon.

**Comment by dviljoen** [comment]
I just discovered I had to prepend "fa-..." to all of my icons.  The context menu documentation and sample code really should be updated to point that out.

**Comment by bbrala** [comment]
https://swisnl.github.io/jQuery-contextMenu/demo/fontawesome-icons.html

The font awesome demo does show that. :)

**Comment by dviljoen** [comment]
And what's more confusing is if you click the "icons" link on the page you shared it gives you a very helpful list of all of the icons.  None of them have "fa-..." preprended.

**Comment by bbrala** [comment]
Made an issue to have a look at improving the docs :)

**Comment by dviljoen** [comment]
ty
