### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by larigyn** [swisnl/jQuery-contextMenu#537]
Hello,

This is an awesome library. I'm looking this for a long time now I already used it in my project. I already read the documentation my question is, I want to click an item inside the context menu and jump to another page or call a modal. How can I configure in this library?

Thanks for any help.

**Comment by bbrala** [comment]
Thanks for the compliment. 

I would probably use the callback functionality for that. You can execute custom code in the callback for a menu item.

https://swisnl.github.io/jQuery-contextMenu/demo/callback.html

**Comment by larigyn** [comment]
Hello Sir, 
I already have this. Do you have other code snippets just an example.

items: {
	"Home": {name: "Home", icon: "fa-home",
	callback: function(itemKey, opt){
         window.location.href= 'home'; //controller from CI
         // this is a toast message
         toastr.info('Home clicked is triggered');   
         return true;
        }  },
*I already successfully triggered a call to another page. Now I want to call a modal.

**Comment by bbrala** [comment]
Of you want to call a modal just call that in De the callback? Not sure what you use for a modal bit just call `$('#element').modal();`?
