### ISSUE TITLE
Not working in mobile.

### ISSUE THREAD

**Issue by larigyn** [swisnl/jQuery-contextMenu#538]
Sir,

It's not working on mobile environment. I tried in browsers developer tools.

**Comment by bbrala** [comment]
When I open the demo on my android phone I can long press to open the menu. Can you give some more details on the issue please?

**Comment by larigyn** [comment]
Hello Sir,

I didn't tried in my own mobile. Currently I'm testing it on browser's developers tools. That's when I change to mobile view and done some trigger events the context menu doesn't appear. Am I doing right?

**Comment by bbrala** [comment]
Think that is how the mobile browser simulates a right click :)
