### ISSUE TITLE
Bootstrap Modal not working in ContextMenu 

### ISSUE THREAD

**Issue by sathyaprakash94** [swisnl/jQuery-contextMenu#539]
Hi there,

I'm trying to open a bootstrap modal when click on the item inside contextMenu. But it fails to open modal.

**The code is as appended below,**
```
<div class="portlet-body">
  <div id="context" data-toggle="context" data-target="#context-menu">
    <p> Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras.
      </p>
  </div>
  <!-- Your custom menu with dropdown-menu as default styling -->
  <div id="context-menu">
    <ul class="dropdown-menu" role="menu">
      <li>
        <a data-target="#demographicmodal" data-toggle="modal">
          <i class="icon-user"></i> New User </a>
      </li>
      <li>
        <a href="javascript:;">
          <i class="icon-present"></i> New Event
          <span class="badge badge-success">4</span>
        </a>
      </li>
    </ul>
  </div>
</div>

<!-- Modal Content -->
<div id="demographicmodal" class="modal fade" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <label data-dismiss="modal" onclick="reloadallergies()" class="fa fa-times pull-right"></label>
        </div>
      </div>
    </div>
  </div>
</div>
```
I could not able to figure out, why the modal is not working. Pls help me to solve this.

**Comment by bbrala** [comment]
Is there any error message? And could you perhapd create a testscase on jsfiddle so i can check and debuig a bit?

**Comment by sathyaprakash94** [comment]
Thanks for your reply. Let me make a fiddle and share you the link. Thanks.

**Comment by bbrala** [comment]
Thanks, that will help a lot.

**Comment by sathyaprakash94** [comment]
Hi,
I have created a fiddle and the link provided below,
https://jsfiddle.net/PrakashS/2vy4u6kv/2/

I'm facing two issues here in the fiddle 
1. Context menu not working 
2. Modal not working

Thanks.

**Comment by larigyn** [comment]
Sir sathyaprakash94,

It works on my modal. I'm using bootstrap.

**Comment by sathyaprakash94** [comment]
@larigyn,

Thanks for your reply. May I know are you worked on the fiddle link provided.

Thanks.

**Comment by larigyn** [comment]
@sathyaprakash94 , 

Sir, take a look. https://jsfiddle.net/PrakashS/2vy4u6kv/2/ 
If it's not working. Just tell me. I'm not in my working environment at this moment.

**Comment by sathyaprakash94** [comment]
H,

Thanks, to spend your valuable time to fix the issue.

**Comment by sathyaprakash94** [comment]
Hi,

It's not working.

**Comment by larigyn** [comment]
@sathyaprakash94 ,

Please provide your snippet. I will fix your problem. Currently It's working on me both on **bootstrap modal** & **izimodal**.

**Comment by larigyn** [comment]
Sir,

Please provide your snippet. I will fixed it. It's working on both **bootstrap modal** & **izimodal**

**Comment by sathyaprakash94** [comment]
Hi,

The code is in the JS fiddle. Both context menu and the bootstrap modal not working.

**Comment by larigyn** [comment]
@sathyaprakash94 ,

Just follow the documentation in context menu. That's what I did.

**Comment by bbrala** [comment]
Hmm, this is not (the unmaintained) `https://github.com/sydcanem/bootstrap-contextmenu/blob/master/bootstrap-contextmenu.js`, but another library. Please use the docs on http://swisnl.github.io/jQuery-contextMenu/ to get things working :)

**Comment by sathyaprakash94** [comment]
Sure thanks.
