### ISSUE TITLE
onclick event

### ISSUE THREAD

**Issue by larigyn** [swisnl/jQuery-contextMenu#543]
Sir,
I tried to create a callback using onclick and I failed. But I tried using buttons. It successfully run.

"delete": {
                      name: "Delete",
                      icon: "fa-trash-o",
                      callback: function(itemKey, opt) {
                      //delete_item is a function that delete 
                        $(this).on('click', delete_item('$item->id'));
                        return true;
                      }
                    },

Can you help me with my problem.

**Comment by bbrala** [comment]
The callbak is called when the item is clicked. In this piece of code you attach the click event handler when the item is clicked. That is wrong.

Perhaps this will work:

```
"delete": {
name: "Delete",
icon: "fa-trash-o",
callback: function(itemKey, opt) {
  //delete_item is a function that delete
  delete_item(itemKey);
  return true;
}
},
```

**Comment by larigyn** [comment]
Sir,
Yes, I was wrong but I manage to fix with the help of some people. Now it's working perfectly in a CRUD operation. Thanks for the TIME.
