### ISSUE TITLE
Disable some options when a specific has been clicked.

### ISSUE THREAD

**Issue by larigyn** [swisnl/jQuery-contextMenu#548]
Sir,
I wanted to implement a disable options when I clicked specific selector. Example I have 4 options in my context menu **(ADD,EDIT,DELETE,QUIT)** , when I click on **TR** option **DELETE** will be disable and also when I clicked on **form** DELETE will be enable, I know this is not the right place to ask but I'm already researching but I can't get any correct answers. I need **HELP**. 

Thanks:)

**Comment by ptdev** [comment]
https://swisnl.github.io/jQuery-contextMenu/docs/items.html#disabled

**Comment by larigyn** [comment]
@ptdev ,

Sir, What I want is to **disabled** ONE of the menu list when a specific **selector** has been triggered

**Comment by ptdev** [comment]
Well I think that's exactly what's on that docs page I linked.

Or maybe I didn't understand what you need exactly. Isn't it just to make one of the context menu options disabled and unclickable ?

**Comment by bbrala** [comment]
You can just build the the menu on demand maybe, and there check what properties are on the tr?

https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
