### ISSUE TITLE
Incorrect html5 polyfil support check

### ISSUE THREAD

**Issue by akamustang** [swisnl/jQuery-contextMenu#549]
There is a comment that says:

```
// if <command> or <menuitem> are not handled by the browser,
// or options was a bool true,
// initialize $.contextMenu for them
```

The code that is meant to check this is:
`(!$.support.htmlCommand && !$.support.htmlMenuitem)`

However this does not operate as described in the comment if one exists and the other doesn't, for example Firefox 54.0.1 has support for `<menuitem>`, but not for `<command>`.

The correct code should either be:
`!($.support.htmlCommand && $.support.htmlMenuitem)`
Or:
`(!$.support.htmlCommand || !$.support.htmlMenuitem)`

**Comment by bbrala** [comment]
Hmm, that seems unfortunate, thanks for reporting :)

**Comment by bbrala** [comment]
Think the comment is wrong, if the browser support any of the two, it should return false, because then you can use the native menu if you like, unless you force the menu to be replaced.
