### ISSUE TITLE
Uncaught TypeError: opt.$menu.css(...)[opt.animation.show] is not a function

### ISSUE THREAD

**Issue by ratajs** [swisnl/jQuery-contextMenu#551]
Uncaught TypeError: opt.$menu.css(...)[opt.animation.show] is not a function

jquery.contextMenu.js:998
hide @ jquery.contextMenu.js:1072
hideMenu @ jquery.contextMenu.js:907
dispatch @ jquery-3.1.1.slim.min.js:3
q.handle @ jquery-3.1.1.slim.min.js:3
trigger @ jquery-3.1.1.slim.min.js:3
(anonymous) @ jquery-3.1.1.slim.min.js:3
each @ jquery-3.1.1.slim.min.js:2
each @ jquery-3.1.1.slim.min.js:2
trigger @ jquery-3.1.1.slim.min.js:3
(anonymous) @ jquery.contextMenu.js:511
jquery.contextMenu.js:998 Uncaught TypeError: opt.$menu.css(...)[opt.animation.show] is not a function

**Comment by bbrala** [comment]
Could you please provide more information, a random error is not much to work with.

**Comment by ratajs** [comment]
I tried it again with newer version of jQuery and now it's working.
With 1.9.1 isn't working.

**Comment by bbrala** [comment]
1.9.1 is rather old on the 1.x  branch. Glad is was just a jQuery issue.
