### ISSUE TITLE
jsTree-style icon definitions

### ISSUE THREAD

**Issue by pvlasov** [swisnl/jQuery-contextMenu#552]
jsTree (https://www.jstree.com/docs/html/) has a neat approach to icon definition - if it contains a slash then it is URL, otherwise it is a class. This allows to use Bootstrap glyphs, FontAwesome icons and images in the same menu. It'd be really nice to to see the same in you product.

**Comment by bbrala** [comment]
That would work, currently you can so this by returning a function for the icon option. This was the solution to avoid backwards compatibility breaks.
