### ISSUE TITLE
Allow for middle click trigger

### ISSUE THREAD

**Issue by francois2oo86** [swisnl/jQuery-contextMenu#554]
Not sure how do-able this is, but I would like the trigger to be middle-click. Based on the docs, it looks like only left click or right click are allowed but maybe I am missing something?

**Comment by bbrala** [comment]
Not possible currently. But you could manually trigger the menu through https://swisnl.github.io/jQuery-contextMenu/docs/events.html#contextmenu

Combined with the trigger option set to 'none'.

**Comment by francois2oo86** [comment]
Thanks a lot for your answer! Will look into it!
