### ISSUE TITLE
How to use the x,y position inside the callback function?

### ISSUE THREAD

**Issue by KainLaVey** [swisnl/jQuery-contextMenu#557]
Hi there,

iam using the context menu to create new elements on a map.
To place this elements i need the x and y position of the contextmenu (where i "right clicked) inside the callback function.

Iam reading the documentation and iam sure this is possible. But i dont get it.

Here the code

```
    $.contextMenu(
        {
            selector: ".map",
            items: {
                addMark: {
                    icon: function (opt, $itemElement, itemKey, item) {
                        $itemElement.html('<i class="fa fa-square-o" aria-hidden="true"></i> Add Mark ' + opt.selector);
                        return 'context-menu-icon-updated';
                    },
                    callback: function () {
                        $(this).append('<div class="mark" style="position:absolute;top:???; left:???;"</div>');
                    }
                }
            }
        });
```
and in the callback function (where the '???' are right now) i need the x/y position of the mouseposition where i right clicked

Hope you can help me out here! <3

**Comment by dwalkz** [comment]
Not sure your use case, but I had to do something similar. Only difference is that my menu is rebuilt on each click. But the "build" method of the contextMenu plugin does pass in the mouse event, so what I've done basically is I have a standard "blank" menu and, in the build function, I set the various items to enabled or disabled based on what was clicked on. 
`
$.contextMenu({
        selector: '#dockSectionCanvas',
        build: function($trigger, evt){

            var menu = deepclone(standardMenu);

            menu.items.paste.callback = function(key, opt){
                activeQuoteInstance.pasteSelected(eevt); //pass down the mouse event that created the context, though it can probably just go to instance.selecting position
            };

            if(activeQuoteInstance.activePan){
                return false;
            }

            if(!activeQuoteInstance.somethingSelected() || activeQuoteInstance.selectedObjects.length === 1) {
                //If nothing is selected or only one item is selected, check what's directly under the mouse cursor
                activeQuoteInstance.findSelectedByClick(e.offsetX, e.offsetY);
                activeQuoteInstance.drawEverything();
            }

            if(activeQuoteInstance.somethingSelected()){
                var sel = activeQuoteInstance.selectedObjects[0];
                activeQuoteInstance.drawEverything();

                menu.items.delete.disabled = false;
                menu.items.delete.visible = true;
                menu.items.copy.disabled = false;
                menu.items.paste.disabled = true;
            }

            if(activeQuoteInstance.disableCopy()){
                menu.items.copy.disabled = true;
            }

            menu.items.paste.disabled = !(activeQuoteInstance.copied.length > 0); //if there's something copied, allow them to paste it

            return menu;
        }
    });
`

There in that fourth or 5th line, you can see me passing down the mouse event through the callback by setting the callback at build time

**Comment by bbrala** [comment]
Hmm, i've seen issues regarding missing original events a few times. Perhaps i should build a way to get always be able to get the original event, not only the internal.
