### ISSUE TITLE
When vertical overflow, shift into viewport instead of flip

### ISSUE THREAD

**Issue by zcyzcy88** [swisnl/jQuery-contextMenu#560]
This is now (flip):
<img width="338" alt="jQuery contextMenu" src="https://user-images.githubusercontent.com/15178410/29222172-05e4021c-7ef4-11e7-99a2-7a82705fe79e.png">

---

This is expect (shift):
![Mac OS](https://user-images.githubusercontent.com/15178410/29222107-ba0f201a-7ef3-11e7-8832-d9d2bd1f2f21.jpg)

---

This also make behavior same as submenu (shift):
<img width="642" alt="jQuery contextMenu" src="https://user-images.githubusercontent.com/15178410/29222335-a16223ea-7ef4-11e7-8036-6a050cde5a85.png">

**Comment by bbrala** [comment]
Thanks for the report :)

The thing is, this behaviour is default for Mac, but not for Windows. I don't feel this is really an issue that needs to be addressed. Even though you are right the submenu kinda behaves like that.
