### ISSUE TITLE
Conditional Submenu

### ISSUE THREAD

**Issue by mtwallet** [swisnl/jQuery-contextMenu#569]
Hi All,

I am using the context menu for as a means to switch layout on a page. I want the menu to only show options that are relevant to the number of items that are on the page because of the sheer number of options that will be available to the user. For example if there are 3 items on a page I only want to display the layouts available that are combinations of 3 (vertical, horizontal, diagonal, hero etc). Please see attached image.

![screen shot 2017-09-26 at 10 51 59](https://user-images.githubusercontent.com/1025398/30854202-e5a0057c-a2a8-11e7-9b7c-f99ff891ce35.png)

Is there a way to render out conditional submenus or hide submenus based on the returned item length when the user right clicks on the page?

I hope that makes sense and many thanks in advance.

**Comment by bbrala** [comment]
There are multiple ways to do this. One wat is a [callback for visibility](http://swisnl.github.io/jQuery-contextMenu/docs/items.html#visible) another is to build the submenu [items dynamicly on open](https://swisnl.github.io/jQuery-contextMenu/docs.html#build).

You can also maybe use the [update command to refresh](https://swisnl.github.io/jQuery-contextMenu/docs.html#update-contextmenu-state) visibility if you just want to use the `visibility` callback.

Demos:
https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html
