### ISSUE TITLE
[docs] Add set-up section

### ISSUE THREAD

**Issue by rs2** [swisnl/jQuery-contextMenu#570]
Apparently it takes more than just a reference to a minified `css` and `js` to get started.

It would be useful to have a few lines in the documentation explaining best practices to avoid hacky solutions.

**Comment by bbrala** [comment]
What extra steps did you need to do to get things running then? I kinda agree the docs could get some attention, but i'm quite interested in specifics.

**Comment by bbrala** [comment]
Closed due to inactivity. A getting started section has been added to the documentation.
