### ISSUE TITLE
callback docs are wrong

### ISSUE THREAD

**Issue by tisdall** [swisnl/jQuery-contextMenu#571]
The [docs for callback](https://swisnl.github.io/jQuery-contextMenu/docs/items.html#callback) say that it takes 4 args and they are `(itemKey, opt, rootMenu, originalEvent)`.  However, [looking at the source code](https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L904) shows this: `callback.call(root.$trigger, key, root, e)`.  So, the docs should drop the "rootMenu" as there's only 3 args passed and the third is the event.  (maybe the docs should also state that `this` is assigned to be `opt.$trigger`)

**Comment by tisdall** [comment]
... `originalEvent` should probably just be `event` as the event passed is a regular jQuery event and the "original" is an attribute off of that passed event.

In other words, if you access the value that's passed (let's call it `event`) you can see that it has the original event as an attribute (so `event.originalEvent` is the actual original event, not the passed in value `event`).

**Comment by bbrala** [comment]
Hmm, good point. It should at least correctly mention how it works now. Thanks for pointing this out.
