### ISSUE TITLE
Submenus at wrong position when combining with Bootstrap

### ISSUE THREAD

**Issue by omsiqveland** [swisnl/jQuery-contextMenu#577]
Im using Bootstrap v3 in my project, which makes the submenus look like this:
![image](https://user-images.githubusercontent.com/23151775/31666718-84467260-b34d-11e7-8723-719edf2554d6.png)
It appears to be due to Bootstrap defining box-sizing: border-box; for all elements by default, but the jquery-contextmenu calculates its submenu coordinates as if based on box-sizing: content-box.
Hence, adding the following css solves my problem:
.context-menu-item {
    box-sizing: content-box;
}

Since contextmenu requires its items to be box-sizing: content-box; this should be added by default to jquery-contextmenu.css?

**Comment by bbrala** [comment]
Hmm, good point, thanks for reporting.
