### ISSUE TITLE
dist folder contains older code

### ISSUE THREAD

**Issue by dxoxp** [swisnl/jQuery-contextMenu#578]
In the 2.6.2 release, the "dist" folder has a "jquery.contextMenu.js" file with a copyright version indicator of 2.5.0.  Additionally, the code itself appears to actually be the older 2.5.0 code.

In the 2.5.0 release and prior, it appears that the code in the "src" and "dist" was kept in sync.

It this discrepancy between the "src" and "dist" folders expected?

**Comment by bbrala** [comment]
Wow, nice catch... Well, that was 2 versions without a rebuild of the dist. Thanks for sending out the issue.
