### ISSUE TITLE
The activated event is called without parameters

### ISSUE THREAD

**Issue by dxoxp** [swisnl/jQuery-contextMenu#580]
The "activated" event appears to be called without the "options" parameter.  This makes it more difficult to use this event, because information that would otherwise be exposed in the "options" must be discovered in other ways or remembered in earlier events (show).

The documentation at https://swisnl.github.io/jQuery-contextMenu/docs.html#events seems to indicate that the "activated" event is intended to have an "options" parameter.

**Comment by bbrala** [comment]
Thanks for reporting this issue. That seems like a problem yeah.
