### ISSUE TITLE
custom icons miss-positioned

### ISSUE THREAD

**Issue by mansoor-omrani** [swisnl/jQuery-contextMenu#581]
Hi

Based on the method described in documentations, when we use a callback to set a custom icon for menu items (such as a bootstrap glyphicon), the icon is not positioned correctly. It is indented to the right like the text of the menu item.

In fact the css class that is applied to the text of menu item which creates some padding is also applied to the icon, makes it leaned to right.

I was forced to apply another class to the <span class="glyphicon"> like below to move it a little to the left.

li.context-menu-item span.glyphicon {
   margin-left: -20px;
   margin-right: 5px;
}

**Comment by bbrala** [comment]
I would advise to use font-awesome, that integration is properly tested. But should you want different icons then yeah, you might need to add some custom CSS unfortunately.
