### ISSUE TITLE
html5 menu searchable select

### ISSUE THREAD

**Issue by adnredwan77** [swisnl/jQuery-contextMenu#582]
Hi, I'm using html5 select  menu, and need to search the select
Menu

 <menu id="html5menu" style="display:none" class="data-title">
  <div class="top_search title_right input-group" >
        <input type="text" class="form-control" id="txtSearch" placeholder="Search for Items..." />
        <span class="input-group-btn">
            <a href="#" class="btn btn-sm btn-primary" onclick="getItem()">Go</a>
            </span>
       </div>
    <select class="form-control" asp-items="ViewBag.items" multiple size="10">
        <option disabled selected value="">Select Diagnose</option>
    </select>
    <hr>
    <command label="Save" onclick="save()">
<div class="top_search title_right input-group" >
        <input type="search" class="form-control" id="txtSearch" placeholder="Search for Item..." />
        <span class="input-group-btn">
            <a href="#" class="btn btn-sm btn-primary" onclick="getItem()">Go</a>
            </span>
       </div>
    <select class="form-control" asp-items="ViewBag.items" multiple size="10">
        <option disabled selected value="">Select  #Item</option>
    </select>
    <hr>
    <command label="Save" onclick="save()">
</menu>

context menu

$.contextMenu({
        selector: 'polygon',
        trigger: 'right',
        className: 'data-title',
        animation: { duration: 250, show: 'fadeIn', hide: 'fadeOut' },
        items: $.contextMenu.fromMenu($('#html5menu'))
    });

search 

 function getItem()
    {
        var str = $('#txtSearch').val();
                 $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetItemStr", "Codes")?str=' + str,
                    success: function (data) {
                        $('#context-menu-select-input-key3').empty();
                          $.each(data, function () {
                            $('#context-menu-select-input-key3').append($("<option  />").val(this.id).text(this.name));
                        });
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        console.log(errorThrown);
                      return false;
                    }
            });
    }

**The problem is  $('#txtSearch').val() return blank and the search function fails**

**Comment by bbrala** [comment]
It would really help to make a jsfiddle with this issue. Could you make one please?

**Comment by adnredwan77** [comment]
Sorry, I've no time this week, may be next week.
working around this I'm using popup modal.

**Comment by adnredwan77** [comment]
I'm so sorry about late in response.
The issue was that I've more than one input text with the id : txtSearch
after changing the id it works fine 👍
