### ISSUE TITLE
Creating a context menu within a callback function (Sigma JS)

### ISSUE THREAD

**Issue by ashokkbhaskar** [swisnl/jQuery-contextMenu#594]
Is it possible to launch a context menu from within a callback for a separate event? I have a [Sigma JS](http://sigmajs.org/) container div with the id 'sigma-container', which has a bind() function that gets called when clicking a graph node. In the callback passed to bind(), I'd like to launch a context menu which can be initialized with graph data accessible from the bind() function, like the node id/label strings. Calling $.contextMenu({...}); in the callback, however, doesn't work. Am I invoking it wrong?

**Comment by Knochenmark** [comment]
https://swisnl.github.io/jQuery-contextMenu/docs.html#build

I am not exactly sure, but isn't the build callback what you need? The contextmenu will be created when clicking and you should be able to pass your graph data that is required to create your menu.

**Comment by bbrala** [comment]
You should be able to do this with the build callback yeah, just check for certain values in that function.

**Comment by ashokkbhaskar** [comment]
Thanks - what is the $triggerElement parameter?

Is the $(function(){ $.contextMenu({...build:...}) }) invocation a top-level declaration, or is that supposed to go inside the clickNode event callback?

**Comment by bbrala** [comment]
That is the element that the menu was bound to. And the build option is indeed a top level decleration.

**Comment by bbrala** [comment]
Closed due to inactivity.
