### ISSUE TITLE
Seperators are missing a visible option

### ISSUE THREAD

**Issue by Knochenmark** [swisnl/jQuery-contextMenu#596]
The seperators are missing a visible option or is there any possibility to pass that argument somehow?
The problem is, their value is just a string and not an object.

**Comment by bbrala** [comment]
You can use `{type: 'cm_seperator'}` if you need an object. :)

**Comment by Knochenmark** [comment]
Ok, i will try that. Thanks

**Comment by bbrala** [comment]
To be honest, the code accepts both, was a type but didn't want to break compatibility. So just use the correct spelling. I will probably remove this in 3.0 :)

**Comment by Knochenmark** [comment]
haha ok, thanks for the info. I didn't notice this myself, since i basically just copy/pasted the object you linked above :)

**Comment by Jogii** [comment]
{type: 'cm_seperator', visible : false} does not work..  :(
