### ISSUE TITLE
jQuery contextMenu works in Win 7 IE 11

### ISSUE THREAD

**Issue by jt4000** [swisnl/jQuery-contextMenu#600]
![l1](https://user-images.githubusercontent.com/14993569/35509743-ac17225e-04f5-11e8-818e-c013610502de.png)

-------------------------------------------

When I use Browserling (https://www.browserling.com/) and select windows 7 and IE 11, this jQuery contextMenu works.

Does somebody have installed win 7 with IE 11 and test  jQuery contextMenu works?

Thank you!

**Comment by bbrala** [comment]
I think the error was in the connection to browserstack. It seems the tests sometimes fail without reason. It does support ie11.

**Comment by bbrala** [comment]
Yeah, just confirmed, everything is fine :)
