### ISSUE TITLE
Lacks something...

### ISSUE THREAD

**Issue by mtugnoli** [swisnl/jQuery-contextMenu#603]
I'm trying to make a dynamic menu based on the selected item, but this news really surprised me...
https://github.com/swisnl/jQuery-contextMenu/issues/579
How is possible ?

I think jQuery contextMenu is a really powerful plugin but it still lacks something ...

**Comment by bbrala** [comment]
3.0 should fix this, but that is currently in beta :)

**Comment by mtugnoli** [comment]
I’ve download 3.0,  but how can get html element  ?

In this sample the single element of .context-menu-one class ?

 

    $(function() {

        $.contextMenu({

            selector: '.context-menu-one', 

            callback: function(key, currentMenuData) {

                var m = "clicked: " + key;

                window.console && console.log(m) || alert(m); 

            },

            items: {

                "edit": {name: "Edit", icon: "edit"},

                "cut": {name: "Cut", icon: "cut"},

               copy: {name: "Copy", icon: "copy"},

                "paste": {name: "Paste", icon: "paste"},

                "delete": {name: "Delete", icon: "delete"},

                "sep1": "---------",

                "quit": {name: "Quit", icon: function(){

                    return 'context-menu-icon context-menu-icon-quit';

                }}

            }

        });

    });

 

 

Da: Björn Brala [mailto:notifications@github.com] 
Inviato: mercoledì 31 gennaio 2018 17:03
A: swisnl/jQuery-contextMenu <jQuery-contextMenu@noreply.github.com>
Cc: mtugnoli <mtugnoli@libero.it>; Author <author@noreply.github.com>
Oggetto: Re: [swisnl/jQuery-contextMenu] Lacks something... (#603)

 

3.0 should fix this, but that is currently in beta :)
