### ISSUE TITLE
use this in easyui

### ISSUE THREAD

**Issue by sogoodgithub** [swisnl/jQuery-contextMenu#605]
pls, how to use this in easyui-grid

**Comment by bbrala** [comment]
Not sure, what have you tried until now?

**Comment by sogoodgithub** [comment]
I solve  it, by add gird event listener: 
	 onRowContextMenu:function(e,index,row){
			    $("#list_data").datagrid("selectRow",index);
			    var  $trigger = $('#myBody .datagrid-row');
   			 	$trigger.data('row',row);
			    if (row) {
			    	//nedd to modify menu item state
			    	pcapFile = row.pcapFile;
			    	$trigger.contextMenu(!isEmpty(pcapFile));
			    }
  			}
 	 }); 

//below is the  contextmenu
    $.contextMenu(   			 {
    		selector: "#myBody .datagrid-row",
  	        callback: function(key, options) {
   			   var m = "clicked: " + key;
              	window.console && console.log(m) || alert(m); 
              },
             items: {
                	"download": {name: "下载抓包文件", icon: "fa-file-archive-o",callback:
                		 // downLoadPcapFile
                		 function(){ 
                		    var row = this.data('row');
                		    return downLoadPcapFile();}
                	     }
            }
	 });

**Comment by bbrala** [comment]
Glad to hear you fixed it :)
