### ISSUE TITLE
set direction for submenu

### ISSUE THREAD

**Issue by eman1986** [swisnl/jQuery-contextMenu#609]
seems like submenus always go to the right, but in some cases I'm seeing things got lost by the browser if the context button is too far to the right of the screen, so an option to set it to go to the left would be of great help.

**Comment by bbrala** [comment]
If you include the [jquery.ui.position.min.js](https://github.com/swisnl/jQuery-contextMenu/blob/master/dist/jquery.ui.position.min.js) file it should be a lot smarter about opening inside the window at all times. :)

**Comment by eman1986** [comment]
good to know, that fixed it
