### ISSUE TITLE
Font awesome height li

### ISSUE THREAD

**Issue by babajem** [swisnl/jQuery-contextMenu#610]
Hello

When I use some font awesome icons, the height of li is smaller.

You can even see it in the documentation : 
https://swisnl.github.io/jQuery-contextMenu/demo.html
26.38px 
https://swisnl.github.io/jQuery-contextMenu/demo/fontawesome-icons.html
22.38px

I search and the problem come from line-height inside .fa{} declaration

so you just have to add : 
`.context-menu-icon.context-menu-icon--fa {
line-height: inherit;
}`

**Comment by bbrala** [comment]
Fixed, thanks for the report.
