### ISSUE TITLE
Visible fires twice

### ISSUE THREAD

**Issue by agentselect** [swisnl/jQuery-contextMenu#612]
I've tried this with even just a single list item and it seems that the visble() function always fires twice - this behaviour also occurs in V3 Beta.

This is pretty problematic when using Ajax calls to determine whether an item should be visible / invisible as it makes 2 trips to the Ajax call.

**Comment by bbrala** [comment]
Yeah that is rather nasty indeed. Thanks for the report.

**Comment by bbrala** [comment]
The menu checked `visible` status twice, once to check if the menu should be opened and once more when the menu was opened. The logic all moved to the `show` method now so the check is only done once. 

Thanks again for the report.
