### ISSUE TITLE
Binding visible() to an Ajax request

### ISSUE THREAD

**Issue by agentselect** [swisnl/jQuery-contextMenu#614]
I'm trying to programatically determine whether a menu item should be visible or not by doing a database query and returning a true / false from that.

However it never gets the chance to correctly fire even with a promise() e.g

 visible: function (key, opt) {

      someAjaxFunction(parameter).done(function (data) {

         // correctly gets data
         return data
     });

    // anything here will always fire
}

I can log the result of the data but visible() always receives false -> it won't wait for the result of the function that checks whether it should be true or false.

I've also tried:

visible:

     $.when({foo: 'bar'}).done(function(){

          // console.log('triggered');
          return true

    })

This fires the log to the console but still always returns false - even without the Ajax call.

Do you have any workaround for this?

**Comment by bbrala** [comment]
Hmm, yeah a workaround could be using a global variable with visbility state. Then telling the menu to update the states.

https://swisnl.github.io/jQuery-contextMenu/docs.html#update-contextmenu-state

Pseudo code

```
window.menuVisibility = {
    myDynamicMenuItem: true
}

someAjaxFunction(parameter).done(function (data) {
    // correctly gets data
    if (data.shouldBeVisible) {
        window.menuVisibility.myDynamicMenu = true;
    } else {
        window.menuVisibility.myDynamicMenu = false;
    }
    $.contextMenu('update') // update all open menus
});

$.contextMenu({
    selector: 'span.context-menu',
    events: {
        show: function (options) {
            someAjaxFunction(parameter);
        }
    }
});
```

I think something in that direction should work.

**Comment by bbrala** [comment]
Closed due to inactivity.
