### ISSUE TITLE
Make submenu width "auto"

### ISSUE THREAD

**Issue by bhuvidya** [swisnl/jQuery-contextMenu#642]
Is there a quick and neat way, via CSS, or plugin options, to allow submenus to **not** inherit width from toplevel menu, but instead have an auto-width, up to a limit? I tried applying `max-width` to `.context-menu-list`, but this doesn't effect an inherited width from the toplevel menu.

**Comment by bbrala** [comment]
You do need to do this with CSS only, shouldn't you also specify something like `width:auto;`  on the elements then? CSS is not really my strong suit :)

**Comment by bbrala** [comment]
Closed due to inactivity.
