### ISSUE TITLE
when use fontawesome ,use the rote ,some thing is wrong

### ISSUE THREAD

**Issue by allen3371** [swisnl/jQuery-contextMenu#646]
when rote hte icon ,the menu roted too

...
"split":
              {
                name: "split",
                icon: "fa-columns fa-rotate-90",
.....

![image](https://user-images.githubusercontent.com/28289993/40636137-2a3c75b0-6330-11e8-8e19-9295742d530b.png)

**Comment by bbrala** [comment]
This will be fixed in the new release, but only for the new font awesome 5. It will create seperate elements for the icons instead of using the row itself.
