### ISSUE TITLE
Expose triggered mouse event for the 'show'/'hide' callbacks

### ISSUE THREAD

**Issue by rromanchenko** [swisnl/jQuery-contextMenu#662]
Hello guys.

I wonder, if there is an ability to access triggered mouse event in 'show'/'hide' callbacks? I would like to check if shift/ctrl/meta key is pressed inside of these callbacks, and for this an original mouse event will be needed.

Thanks.

**Comment by bbrala** [comment]
In the currecnt version this is not possible unfortunately. The 3.x version will support this, and will always send through the original events.

**Comment by rromanchenko** [comment]
Thanks.
