### ISSUE TITLE
Cursor issue when context menu is shown

### ISSUE THREAD

**Issue by nadavb** [swisnl/jQuery-contextMenu#671]
I am creating a context menu on an element which contains some editable text.
When the context menu is shown, the cursor over the text is changed (I don't want it) from being `text` to 'default'.
I don't know why. Is it done programmatically inside the jquery contextMenu code, or is it because the contextMenu changes the focus or something?
I think it's because of the context-menu-layer which covers the whole screen, and affects other elements besides the context-menu. Is the context-menu-layer necessary for the functionality of the contextMenu? How can we avoid this problem?

**Comment by bbrala** [comment]
Seems like this CSS is the reason. Perhaps you could overwrite this?

```
.context-menu-input.context-menu-hover {
  cursor: default;
  color: $context-menu-text-color;
}
```
