### ISSUE TITLE
Two input selects on submenu

### ISSUE THREAD

**Issue by roghellman** [swisnl/jQuery-contextMenu#679]
I have two input selects on a submenu and want to update the options in the second select based on the value selected in the first input select.

I've tried multiple variations to implement this but all have failed.  Is this possible to achieve?
I'm apparently having difficulty understanding the documentation.

**Comment by bbrala** [comment]
Hmm, this is pretty specific. You should be able to select the element with jQuery and add the proper events. But finding the right select might be hard. If you have a jsfiddle i might be able to help you out.

**Comment by roghellman** [comment]
Björn:

Thank you for the offer.  It would be nice to do, but not worth the
effort.

Rogers

**Comment by bbrala** [comment]
Ok :)
