### ISSUE TITLE
Dynamically (programmatically) populate context menu after right click event

### ISSUE THREAD

**Issue by jochemstoel** [swisnl/jQuery-contextMenu#681]
I keep getting stuck making the context menu decide the menu items on/immediately after the right click event. In all the examples the menu items are predefined for each selector. How would I go about implementing this properly?

**Comment by bbrala** [comment]
You should be able to do this with the following demo:
https://swisnl.github.io/jQuery-contextMenu/demo/async-create.html

**Comment by jochemstoel** [comment]
There is a small error in this example you provided.  It does not _preventDefault()_ on right click. Chrome's native context menu opens too.
