### ISSUE TITLE
ContextMenu in Fullscreen

### ISSUE THREAD

**Issue by patrickluethi** [swisnl/jQuery-contextMenu#692]
I added a contextmenu to a div. Everything works fine now i set the div to fullscreen with .requestFullscreen(). The div is now in fullscreen but the contextMenu doesnt appear anymore.

What do i need to change to make it appear?

Here is my code: 

```
$.contextMenu({
            selector: '.fixed-size-info',
            zIndex: 100,
            callback: function(key, options) {
                switch (key) {
                    case 'fullscreen':
                        if( window.innerHeight == screen.height) {
                          // browser is fullscreen
                          self._div.exitFullscreen();
                          var target = {
                            parent: self._selectedGuid
                          };
                          self.openParentInfo(target, self);
                        } else {
                          document.getElementById('fixed-size-info').requestFullscreen();
                          // openFullscreen(document.getElementById('fixed-size-info'));
                          // openFullscreen(self._div);
                          self.table.style.height = '100%';
                          var target = {
                            parent: self._selectedGuid
                          };
                          self.openParentInfo(target, self);
                        }
                        break;

                    default:
                        console.log(key);
                        console.log(options);
                }
            },
            items: {
                "fullscreen": {
                    name: "Fullscreen",
                    icon: "fas fa-expand"
                },
                "sep1": "---------",
                "quit": {
                    name: "Quit",
                    icon: function() {
                        return 'context-menu-icon context-menu-icon-quit';
                    }
                }
            }
        });
```

**Comment by bbrala** [comment]
Do you get any errors? And i wonder, if you open the menu manually with javascript, does it display then?

https://swisnl.github.io/jQuery-contextMenu/demo/trigger-custom.html

**Comment by DarthSonic** [comment]
I have the same issue: Problem is when requesting fullscreen for an element (above example: `document.getElementById('fixed-size-info').requestFullscreen();`) then the context menu is still appended to the document.body and is shown below the fullscreen element. I am looking for a way to dynamically append the context menu to the fullscreen element.

**Comment by DarthSonic** [comment]
My workaround is to destroy contextMenu when entering fullscreen and re-init with fullscreen element an "appendTo" fullscreen element. Unfortunately the callback of the contextMenu will not work. I cannot figure out why. When initially loading page non-screen menu is working, after destroy and re-init with appendTo-option set it will not trigger callback.
