### ISSUE TITLE
Extend Context Menu after build

### ISSUE THREAD

**Issue by patrickluethi** [swisnl/jQuery-contextMenu#705]
Is it possible to add new items to the ContextMenu after it was build?

**Comment by patrickluethi** [comment]
So there is no way i can add an item to items after the build?

**Comment by JaZo** [comment]
The method you specify in the build option is called every time the context menu is opened so you can define the items based on some runtime variable. Once your method returns the items and the context menu is open/visible you can't add new items. Please see https://swisnl.github.io/jQuery-contextMenu/docs.html#build.

**Comment by patrickluethi** [comment]
Okay, thank you!
