### ISSUE TITLE
How to disable the context menu altogether.

### ISSUE THREAD

**Issue by GLubomirov** [swisnl/jQuery-contextMenu#708]
Hi,

I need to have the menu appear only in certain situations. How do I disable the menu, after i initialized it.

Greetings,
George

**Comment by bbrala** [comment]
You can disable the trigger by calling a method on the menu. Check the docs for more information.

https://swisnl.github.io/jQuery-contextMenu/docs/plugin-commands.html#disable-a-contextmenu-trigger
