### ISSUE TITLE
build: function($trigger, e) not invoke every right click

### ISSUE THREAD

**Issue by terenyang** [swisnl/jQuery-contextMenu#709]
Hi, I am following the [demo ](https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html) to dynamic create context menu for my web divs,  but when I move mouse and keep right click, the menu doesn't do refresh(build), seems the function not invoked almost every time.
Is there a issue or some mistake I did?
thank you.

**Comment by bbrala** [comment]
You can use the `reposition` option to control if the menu rebuilds when right clicking on another place on the page.

https://swisnl.github.io/jQuery-contextMenu/docs.html#reposition
