### ISSUE TITLE
Prevent right click inside context menu

### ISSUE THREAD

**Issue by cplaiu** [swisnl/jQuery-contextMenu#730]
Hello,  I would like to know if it is possible to avoid right clicking inside the context menu. 

Now when you right click inside it calls the callback function, but I wish it would do nothing and the menu would not close

[CodePen Example](https://codepen.io/cplaiuu/pen/poydLrz)

Thanks

**Comment by bbrala** [comment]
You could try and check in the callback if the `e` (event) was triggered by another mousebutton, then return false. See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
