### ISSUE TITLE
Safari browser contextmenu problem

### ISSUE THREAD

**Issue by kiran112** [swisnl/jQuery-contextMenu#86]
I m using contextMenu plugin in my application, it is working well in ie,firefox,chrome
not working in safari browser 

please suggest me how to make work in safari browser

Thanks
kiran

**Comment by anelad** [comment]
Nope. This issue shouldn't be closed. Here I shared a gif; as you can see Safari has a bug with this contextmenu thing. 

I've written my own code and seen a worse problem; so I googled it, I've found this issue; checked if you have the same problem and -sorry but- yes. I think that's all about a Safari bug, or we are skipping something.

![screenflick movie 3](https://cloud.githubusercontent.com/assets/5767654/25493616/7862ec90-2b7f-11e7-9804-1141b2d84bd0.gif)

**Comment by bbrala** [comment]
Hi, 

Thanks for the comment, and the demo gif, but could you raise a new issue? This one is 4 years old :)

**Comment by anelad** [comment]
I've actually seen it's age after my edit :)  removing all ranges would be bad if someone wants to use menu on selected text btw.
